/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, InstantiateMsg, Module, ExecuteMsg, Uint128, Binary, ReplyOn, OwnershipMessage, Expiration, Timestamp, Uint64, Addr, PermissioningMessage, Permission, Cw20ReceiveMsg, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, BalanceResponse, BlockHeightResponse, ConfigResponse, IsOperatorResponse, KernelAddressResponse, ArrayOfString, OperatorsResponse, PublisherResponse, ContractOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, StateResponse, TypeResponse, UserInfoResponse, VersionResponse, Decimal } from "./LockdropContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class LockdropContractTsExecuteMsgBuilder {
  static receive = ({
    amount,
    msg,
    sender
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    receive: unknown;
  }>["receive"]>): ExecuteMsg => {
    return {
      receive: ({
        amount,
        msg,
        sender
      } as const)
    };
  };
  static depositNative = (): ExecuteMsg => {
    return {
      deposit_native: ({} as const)
    };
  };
  static withdrawNative = ({
    amount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw_native: unknown;
  }>["withdraw_native"]>): ExecuteMsg => {
    return {
      withdraw_native: ({
        amount
      } as const)
    };
  };
  static claimRewards = (): ExecuteMsg => {
    return {
      claim_rewards: ({} as const)
    };
  };
  static enableClaims = (): ExecuteMsg => {
    return {
      enable_claims: ({} as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static registerModule = ({
    module
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_module: unknown;
  }>["register_module"]>): ExecuteMsg => {
    return {
      register_module: ({
        module
      } as const)
    };
  };
  static deregisterModule = ({
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deregister_module: unknown;
  }>["deregister_module"]>): ExecuteMsg => {
    return {
      deregister_module: ({
        module_idx: moduleIdx
      } as const)
    };
  };
  static alterModule = ({
    module,
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    alter_module: unknown;
  }>["alter_module"]>): ExecuteMsg => {
    return {
      alter_module: ({
        module,
        module_idx: moduleIdx
      } as const)
    };
  };
}
export abstract class LockdropContractTsQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static state = (): QueryMsg => {
    return {
      state: ({} as const)
    };
  };
  static userInfo = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    user_info: unknown;
  }>["user_info"]>): QueryMsg => {
    return {
      user_info: ({
        address
      } as const)
    };
  };
  static withdrawalPercentAllowed = ({
    timestamp
  }: CamelCasedProperties<Extract<QueryMsg, {
    withdrawal_percent_allowed: unknown;
  }>["withdrawal_percent_allowed"]>): QueryMsg => {
    return {
      withdrawal_percent_allowed: ({
        timestamp
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static operators = (): QueryMsg => {
    return {
      operators: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static isOperator = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    is_operator: unknown;
  }>["is_operator"]>): QueryMsg => {
    return {
      is_operator: ({
        address
      } as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static balance = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    balance: unknown;
  }>["balance"]>): QueryMsg => {
    return {
      balance: ({
        address
      } as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static module = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    module: unknown;
  }>["module"]>): QueryMsg => {
    return {
      module: ({
        id
      } as const)
    };
  };
  static moduleIds = (): QueryMsg => {
    return {
      module_ids: ({} as const)
    };
  };
}