/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { ComponentType, Binary, AndrAddr, InstantiateMsg, AppComponent, CrossChainComponent, ChainInfo, ExecuteMsg, Addr, ReplyOn, Uint128, OwnershipMessage, Expiration, Timestamp, Uint64, Permission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, BalanceResponse, BlockHeightResponse, Boolean, ConfigResponse, String, ArrayOfAppComponent, IsOperatorResponse, KernelAddressResponse, OperatorsResponse, PublisherResponse, ContractOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./AppContractContractTs.types";
export interface AppContractContractTsReadOnlyInterface {
  contractAddress: string;
  getAddress: ({
    name
  }: {
    name: string;
  }) => Promise<String>;
  getComponents: () => Promise<AppComponent>;
  componentExists: ({
    name
  }: {
    name: string;
  }) => Promise<Boolean>;
  getAddressesWithNames: () => Promise<ArrayOfAppComponent>;
  config: () => Promise<ConfigResponse>;
  owner: () => Promise<ContractOwnerResponse>;
  operators: () => Promise<OperatorsResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  isOperator: ({
    address
  }: {
    address: string;
  }) => Promise<IsOperatorResponse>;
  version: () => Promise<VersionResponse>;
  balance: ({
    address
  }: {
    address: AndrAddr;
  }) => Promise<BalanceResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
}
export class AppContractContractTsQueryClient implements AppContractContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getAddress = this.getAddress.bind(this);
    this.getComponents = this.getComponents.bind(this);
    this.componentExists = this.componentExists.bind(this);
    this.getAddressesWithNames = this.getAddressesWithNames.bind(this);
    this.config = this.config.bind(this);
    this.owner = this.owner.bind(this);
    this.operators = this.operators.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.isOperator = this.isOperator.bind(this);
    this.version = this.version.bind(this);
    this.balance = this.balance.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
  }

  getAddress = async ({
    name
  }: {
    name: string;
  }): Promise<String> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_address: {
        name
      }
    });
  };
  getComponents = async (): Promise<AppComponent> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_components: {}
    });
  };
  componentExists = async ({
    name
  }: {
    name: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      component_exists: {
        name
      }
    });
  };
  getAddressesWithNames = async (): Promise<ArrayOfAppComponent> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_addresses_with_names: {}
    });
  };
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  operators = async (): Promise<OperatorsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operators: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  isOperator = async ({
    address
  }: {
    address: string;
  }): Promise<IsOperatorResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_operator: {
        address
      }
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  balance = async ({
    address
  }: {
    address: AndrAddr;
  }): Promise<BalanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {
        address
      }
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
}
export interface AppContractContractTsInterface {
  contractAddress: string;
  sender: string;
  addAppComponent: ({
    component
  }: {
    component: AppComponent;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimOwnership: ({
    name,
    newOwner
  }: {
    name?: string;
    newOwner?: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  proxyMessage: ({
    msg,
    name
  }: {
    msg: Binary;
    name: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAddress: ({
    addr,
    name
  }: {
    addr: string;
    name: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  assignAppToComponents: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setPermission: ({
    action,
    actor,
    permission
  }: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removePermission: ({
    action,
    actor
  }: {
    action: string;
    actor: AndrAddr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissionAction: ({
    action
  }: {
    action: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class AppContractContractTsClient implements AppContractContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.addAppComponent = this.addAppComponent.bind(this);
    this.claimOwnership = this.claimOwnership.bind(this);
    this.proxyMessage = this.proxyMessage.bind(this);
    this.updateAddress = this.updateAddress.bind(this);
    this.assignAppToComponents = this.assignAppToComponents.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.setPermission = this.setPermission.bind(this);
    this.removePermission = this.removePermission.bind(this);
    this.permissionAction = this.permissionAction.bind(this);
  }

  addAppComponent = async ({
    component
  }: {
    component: AppComponent;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_app_component: {
        component
      }
    }, fee, memo, _funds);
  };
  claimOwnership = async ({
    name,
    newOwner
  }: {
    name?: string;
    newOwner?: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_ownership: {
        name,
        new_owner: newOwner
      }
    }, fee, memo, _funds);
  };
  proxyMessage = async ({
    msg,
    name
  }: {
    msg: Binary;
    name: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      proxy_message: {
        msg,
        name
      }
    }, fee, memo, _funds);
  };
  updateAddress = async ({
    addr,
    name
  }: {
    addr: string;
    name: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_address: {
        addr,
        name
      }
    }, fee, memo, _funds);
  };
  assignAppToComponents = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      assign_app_to_components: {}
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  setPermission = async ({
    action,
    actor,
    permission
  }: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_permission: {
        action,
        actor,
        permission
      }
    }, fee, memo, _funds);
  };
  removePermission = async ({
    action,
    actor
  }: {
    action: string;
    actor: AndrAddr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_permission: {
        action,
        actor
      }
    }, fee, memo, _funds);
  };
  permissionAction = async ({
    action
  }: {
    action: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permission_action: {
        action
      }
    }, fee, memo, _funds);
  };
}