/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { AndrAddr, InstantiateMsg, ExecuteMsg, Binary, Uint128, Asset, Expiry, Milliseconds, Addr, ReplyOn, OwnershipMessage, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, Cw721ReceiveMsg, Cw20ReceiveMsg, Recipient, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, PercentRate, QueryMsg, OrderBy, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, AuctionIdsResponse, AuctionInfo, Expiration, Timestamp, Uint64, AuctionStateResponse, AuthorizedAddressesResponse, BidsResponse, Bid, BlockHeightResponse, IsCancelledResponse, IsClaimedResponse, IsClosedResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, TypeResponse, VersionResponse } from "./AuctionContractTs.types";
export interface AuctionContractTsReadOnlyInterface {
  contractAddress: string;
  latestAuctionState: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }) => Promise<AuctionStateResponse>;
  auctionState: ({
    auctionId
  }: {
    auctionId: Uint128;
  }) => Promise<AuctionStateResponse>;
  auctionIds: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }) => Promise<AuctionIdsResponse>;
  auctionInfosForAddress: ({
    limit,
    startAfter,
    tokenAddress
  }: {
    limit?: number;
    startAfter?: string;
    tokenAddress: string;
  }) => Promise<AuctionInfo>;
  authorizedAddresses: ({
    limit,
    orderBy,
    startAfter
  }: {
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: string;
  }) => Promise<AuthorizedAddressesResponse>;
  bids: ({
    auctionId,
    limit,
    orderBy,
    startAfter
  }: {
    auctionId: Uint128;
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: number;
  }) => Promise<BidsResponse>;
  isCancelled: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }) => Promise<IsCancelledResponse>;
  isClosed: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }) => Promise<IsClosedResponse>;
  isClaimed: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }) => Promise<IsClaimedResponse>;
  owner: () => Promise<ContractOwnerResponse>;
  ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  appContract: () => Promise<AppContractResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  version: () => Promise<VersionResponse>;
  aDOBaseVersion: () => Promise<ADOBaseVersionResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  rates: ({
    action
  }: {
    action: string;
  }) => Promise<NullableRate>;
  allRates: () => Promise<AllRatesResponse>;
}
export class AuctionContractTsQueryClient implements AuctionContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.latestAuctionState = this.latestAuctionState.bind(this);
    this.auctionState = this.auctionState.bind(this);
    this.auctionIds = this.auctionIds.bind(this);
    this.auctionInfosForAddress = this.auctionInfosForAddress.bind(this);
    this.authorizedAddresses = this.authorizedAddresses.bind(this);
    this.bids = this.bids.bind(this);
    this.isCancelled = this.isCancelled.bind(this);
    this.isClosed = this.isClosed.bind(this);
    this.isClaimed = this.isClaimed.bind(this);
    this.owner = this.owner.bind(this);
    this.ownershipRequest = this.ownershipRequest.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.appContract = this.appContract.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.version = this.version.bind(this);
    this.aDOBaseVersion = this.aDOBaseVersion.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.rates = this.rates.bind(this);
    this.allRates = this.allRates.bind(this);
  }

  latestAuctionState = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }): Promise<AuctionStateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      latest_auction_state: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    });
  };
  auctionState = async ({
    auctionId
  }: {
    auctionId: Uint128;
  }): Promise<AuctionStateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      auction_state: {
        auction_id: auctionId
      }
    });
  };
  auctionIds = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }): Promise<AuctionIdsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      auction_ids: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    });
  };
  auctionInfosForAddress = async ({
    limit,
    startAfter,
    tokenAddress
  }: {
    limit?: number;
    startAfter?: string;
    tokenAddress: string;
  }): Promise<AuctionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      auction_infos_for_address: {
        limit,
        start_after: startAfter,
        token_address: tokenAddress
      }
    });
  };
  authorizedAddresses = async ({
    limit,
    orderBy,
    startAfter
  }: {
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: string;
  }): Promise<AuthorizedAddressesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      authorized_addresses: {
        limit,
        order_by: orderBy,
        start_after: startAfter
      }
    });
  };
  bids = async ({
    auctionId,
    limit,
    orderBy,
    startAfter
  }: {
    auctionId: Uint128;
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: number;
  }): Promise<BidsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      bids: {
        auction_id: auctionId,
        limit,
        order_by: orderBy,
        start_after: startAfter
      }
    });
  };
  isCancelled = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }): Promise<IsCancelledResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_cancelled: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    });
  };
  isClosed = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }): Promise<IsClosedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_closed: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    });
  };
  isClaimed = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }): Promise<IsClaimedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_claimed: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  ownershipRequest = async (): Promise<ContractPotentialOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership_request: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  appContract = async (): Promise<AppContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      app_contract: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  aDOBaseVersion = async (): Promise<ADOBaseVersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      a_d_o_base_version: {}
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  rates = async ({
    action
  }: {
    action: string;
  }): Promise<NullableRate> => {
    return this.client.queryContractSmart(this.contractAddress, {
      rates: {
        action
      }
    });
  };
  allRates = async (): Promise<AllRatesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_rates: {}
    });
  };
}
export interface AuctionContractTsInterface {
  contractAddress: string;
  sender: string;
  receiveNft: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  placeBid: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claim: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAuction: ({
    coinDenom,
    endTime,
    minBid,
    minRaise,
    recipient,
    startTime,
    tokenAddress,
    tokenId,
    whitelist
  }: {
    coinDenom: Asset;
    endTime: Expiry;
    minBid?: Uint128;
    minRaise?: Uint128;
    recipient?: Recipient;
    startTime?: Expiry;
    tokenAddress: string;
    tokenId: string;
    whitelist?: Addr[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  cancelAuction: ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  authorizeTokenContract: ({
    addr,
    expiration
  }: {
    addr: AndrAddr;
    expiration?: Expiry;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deauthorizeTokenContract: ({
    addr
  }: {
    addr: AndrAddr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  rates: (ratesMessage: RatesMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class AuctionContractTsClient implements AuctionContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receiveNft = this.receiveNft.bind(this);
    this.receive = this.receive.bind(this);
    this.placeBid = this.placeBid.bind(this);
    this.claim = this.claim.bind(this);
    this.updateAuction = this.updateAuction.bind(this);
    this.cancelAuction = this.cancelAuction.bind(this);
    this.authorizeTokenContract = this.authorizeTokenContract.bind(this);
    this.deauthorizeTokenContract = this.deauthorizeTokenContract.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.permissioning = this.permissioning.bind(this);
    this.rates = this.rates.bind(this);
  }

  receiveNft = async ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive_nft: {
        msg,
        sender,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  placeBid = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      place_bid: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  claim = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  updateAuction = async ({
    coinDenom,
    endTime,
    minBid,
    minRaise,
    recipient,
    startTime,
    tokenAddress,
    tokenId,
    whitelist
  }: {
    coinDenom: Asset;
    endTime: Expiry;
    minBid?: Uint128;
    minRaise?: Uint128;
    recipient?: Recipient;
    startTime?: Expiry;
    tokenAddress: string;
    tokenId: string;
    whitelist?: Addr[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_auction: {
        coin_denom: coinDenom,
        end_time: endTime,
        min_bid: minBid,
        min_raise: minRaise,
        recipient,
        start_time: startTime,
        token_address: tokenAddress,
        token_id: tokenId,
        whitelist
      }
    }, fee, memo, _funds);
  };
  cancelAuction = async ({
    tokenAddress,
    tokenId
  }: {
    tokenAddress: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_auction: {
        token_address: tokenAddress,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  authorizeTokenContract = async ({
    addr,
    expiration
  }: {
    addr: AndrAddr;
    expiration?: Expiry;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      authorize_token_contract: {
        addr,
        expiration
      }
    }, fee, memo, _funds);
  };
  deauthorizeTokenContract = async ({
    addr
  }: {
    addr: AndrAddr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deauthorize_token_contract: {
        addr
      }
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  permissioning = async (permissioningMessage: PermissioningMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permissioning: permissioningMessage
    }, fee, memo, _funds);
  };
  rates = async (ratesMessage: RatesMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      rates: ratesMessage
    }, fee, memo, _funds);
  };
}