/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { LocalRateType, AndrAddr, Binary, LocalRateValue, Decimal, Uint128, InstantiateMsg, LocalRate, Recipient, PercentRate, Coin, ExecuteMsg, ReplyOn, OwnershipMessage, Expiry, Milliseconds, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, RateResponse, NullableRate, TypeResponse, VersionResponse } from "./RatesContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class RatesContractTsExecuteMsgBuilder {
  static setRate = ({
    action,
    rate
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    set_rate: unknown;
  }>["set_rate"]>): ExecuteMsg => {
    return {
      set_rate: ({
        action,
        rate
      } as const)
    };
  };
  static removeRate = ({
    action
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    remove_rate: unknown;
  }>["remove_rate"]>): ExecuteMsg => {
    return {
      remove_rate: ({
        action
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class RatesContractTsQueryMsgBuilder {
  static rate = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rate: unknown;
  }>["rate"]>): QueryMsg => {
    return {
      rate: ({
        action
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rates: unknown;
  }>["rates"]>): QueryMsg => {
    return {
      rates: ({
        action
      } as const)
    };
  };
  static allRates = (): QueryMsg => {
    return {
      all_rates: ({} as const)
    };
  };
}