"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.KernelContractTsClient = exports.KernelContractTsQueryClient = void 0;
class KernelContractTsQueryClient {
    constructor(client, contractAddress) {
        this.keyAddress = async ({ key }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                key_address: {
                    key
                }
            });
        };
        this.verifyAddress = async ({ address }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                verify_address: {
                    address
                }
            });
        };
        this.channelInfo = async ({ chain }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                channel_info: {
                    chain
                }
            });
        };
        this.recoveries = async ({ addr }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                recoveries: {
                    addr
                }
            });
        };
        this.chainName = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                chain_name: {}
            });
        };
        this.version = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                version: {}
            });
        };
        this.type = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                type: {}
            });
        };
        this.owner = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                owner: {}
            });
        };
        this.client = client;
        this.contractAddress = contractAddress;
        this.keyAddress = this.keyAddress.bind(this);
        this.verifyAddress = this.verifyAddress.bind(this);
        this.channelInfo = this.channelInfo.bind(this);
        this.recoveries = this.recoveries.bind(this);
        this.chainName = this.chainName.bind(this);
        this.version = this.version.bind(this);
        this.type = this.type.bind(this);
        this.owner = this.owner.bind(this);
    }
}
exports.KernelContractTsQueryClient = KernelContractTsQueryClient;
class KernelContractTsClient {
    constructor(client, sender, contractAddress) {
        this.ampReceive = async ({ ctx, messages }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                amp_receive: {
                    ctx,
                    messages
                }
            }, fee, memo, _funds);
        };
        this.send = async ({ message }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                send: {
                    message
                }
            }, fee, memo, _funds);
        };
        this.upsertKeyAddress = async ({ key, value }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                upsert_key_address: {
                    key,
                    value
                }
            }, fee, memo, _funds);
        };
        this.create = async ({ adoType, chain, msg, owner }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                create: {
                    ado_type: adoType,
                    chain,
                    msg,
                    owner
                }
            }, fee, memo, _funds);
        };
        this.assignChannels = async ({ chain, directChannelId, ics20ChannelId, kernelAddress }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                assign_channels: {
                    chain,
                    direct_channel_id: directChannelId,
                    ics20_channel_id: ics20ChannelId,
                    kernel_address: kernelAddress
                }
            }, fee, memo, _funds);
        };
        this.recover = async (fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                recover: {}
            }, fee, memo, _funds);
        };
        this.updateChainName = async ({ chainName }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_chain_name: {
                    chain_name: chainName
                }
            }, fee, memo, _funds);
        };
        this.internal = async (internalMsg, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                internal: internalMsg
            }, fee, memo, _funds);
        };
        this.ownership = async (ownershipMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                ownership: ownershipMessage
            }, fee, memo, _funds);
        };
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.ampReceive = this.ampReceive.bind(this);
        this.send = this.send.bind(this);
        this.upsertKeyAddress = this.upsertKeyAddress.bind(this);
        this.create = this.create.bind(this);
        this.assignChannels = this.assignChannels.bind(this);
        this.recover = this.recover.bind(this);
        this.updateChainName = this.updateChainName.bind(this);
        this.internal = this.internal.bind(this);
        this.ownership = this.ownership.bind(this);
    }
}
exports.KernelContractTsClient = KernelContractTsClient;
