/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, InternalMsg, OwnershipMessage, QueryMsg } from "./KernelContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class KernelContractTsExecuteMsgBuilder {
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static send: ({ message }: CamelCasedProperties<Extract<ExecuteMsg, {
        send: unknown;
    }>["send"]>) => ExecuteMsg;
    static upsertKeyAddress: ({ key, value }: CamelCasedProperties<Extract<ExecuteMsg, {
        upsert_key_address: unknown;
    }>["upsert_key_address"]>) => ExecuteMsg;
    static create: ({ adoType, chain, msg, owner }: CamelCasedProperties<Extract<ExecuteMsg, {
        create: unknown;
    }>["create"]>) => ExecuteMsg;
    static assignChannels: ({ chain, directChannelId, ics20ChannelId, kernelAddress }: CamelCasedProperties<Extract<ExecuteMsg, {
        assign_channels: unknown;
    }>["assign_channels"]>) => ExecuteMsg;
    static recover: () => ExecuteMsg;
    static updateChainName: ({ chainName }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_chain_name: unknown;
    }>["update_chain_name"]>) => ExecuteMsg;
    static internal: (internalMsg: InternalMsg) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
}
export declare abstract class KernelContractTsQueryMsgBuilder {
    static keyAddress: ({ key }: CamelCasedProperties<Extract<QueryMsg, {
        key_address: unknown;
    }>["key_address"]>) => QueryMsg;
    static verifyAddress: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        verify_address: unknown;
    }>["verify_address"]>) => QueryMsg;
    static channelInfo: ({ chain }: CamelCasedProperties<Extract<QueryMsg, {
        channel_info: unknown;
    }>["channel_info"]>) => QueryMsg;
    static recoveries: ({ addr }: CamelCasedProperties<Extract<QueryMsg, {
        recoveries: unknown;
    }>["recoveries"]>) => QueryMsg;
    static chainName: () => QueryMsg;
    static version: () => QueryMsg;
    static type: () => QueryMsg;
    static owner: () => QueryMsg;
}
