/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Uint128, Module, Binary, OwnershipMessage, Uint64, Addr, PermissioningMessage, AMPCtx, AMPMsg, Coin, AndromedaHook, AccountDetails, AppContractResponse, BlockHeightResponse, CoinAllowance, KernelAddressResponse, ArrayOfString, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, TypeResponse, VersionResponse } from "./RateLimitingWithdrawalsContractTs.types";
export interface RateLimitingWithdrawalsContractTsReadOnlyInterface {
    contractAddress: string;
    coinAllowanceDetails: () => Promise<CoinAllowance>;
    accountDetails: ({ account }: {
        account: string;
    }) => Promise<AccountDetails>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
    module: ({ id }: {
        id: Uint64;
    }) => Promise<Module>;
    moduleIds: () => Promise<ArrayOfString>;
    andrHook: (andromedaHook: AndromedaHook) => Promise<Binary>;
}
export declare class RateLimitingWithdrawalsContractTsQueryClient implements RateLimitingWithdrawalsContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    coinAllowanceDetails: () => Promise<CoinAllowance>;
    accountDetails: ({ account }: {
        account: string;
    }) => Promise<AccountDetails>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
    module: ({ id }: {
        id: Uint64;
    }) => Promise<Module>;
    moduleIds: () => Promise<ArrayOfString>;
    andrHook: (andromedaHook: AndromedaHook) => Promise<Binary>;
}
export interface RateLimitingWithdrawalsContractTsInterface {
    contractAddress: string;
    sender: string;
    deposits: ({ recipient }: {
        recipient?: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdrawFunds: ({ amount }: {
        amount: Uint128;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    registerModule: ({ module }: {
        module: Module;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    deregisterModule: ({ moduleIdx }: {
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    alterModule: ({ module, moduleIdx }: {
        module: Module;
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class RateLimitingWithdrawalsContractTsClient implements RateLimitingWithdrawalsContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    deposits: ({ recipient }: {
        recipient?: string | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdrawFunds: ({ amount }: {
        amount: Uint128;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    registerModule: ({ module }: {
        module: Module;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    deregisterModule: ({ moduleIdx }: {
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    alterModule: ({ module, moduleIdx }: {
        module: Module;
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
