/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg, AndromedaHook } from "./MerkleAirdropContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class MerkleAirdropContractTsExecuteMsgBuilder {
    static registerMerkleRoot: ({ expiration, merkleRoot, totalAmount }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_merkle_root: unknown;
    }>["register_merkle_root"]>) => ExecuteMsg;
    static claim: ({ amount, proof, stage }: CamelCasedProperties<Extract<ExecuteMsg, {
        claim: unknown;
    }>["claim"]>) => ExecuteMsg;
    static burn: ({ stage }: CamelCasedProperties<Extract<ExecuteMsg, {
        burn: unknown;
    }>["burn"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
    static registerModule: ({ module }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_module: unknown;
    }>["register_module"]>) => ExecuteMsg;
    static deregisterModule: ({ moduleIdx }: CamelCasedProperties<Extract<ExecuteMsg, {
        deregister_module: unknown;
    }>["deregister_module"]>) => ExecuteMsg;
    static alterModule: ({ module, moduleIdx }: CamelCasedProperties<Extract<ExecuteMsg, {
        alter_module: unknown;
    }>["alter_module"]>) => ExecuteMsg;
}
export declare abstract class MerkleAirdropContractTsQueryMsgBuilder {
    static config: () => QueryMsg;
    static merkleRoot: ({ stage }: CamelCasedProperties<Extract<QueryMsg, {
        merkle_root: unknown;
    }>["merkle_root"]>) => QueryMsg;
    static latestStage: () => QueryMsg;
    static isClaimed: ({ address, stage }: CamelCasedProperties<Extract<QueryMsg, {
        is_claimed: unknown;
    }>["is_claimed"]>) => QueryMsg;
    static totalClaimed: ({ stage }: CamelCasedProperties<Extract<QueryMsg, {
        total_claimed: unknown;
    }>["total_claimed"]>) => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
    static module: ({ id }: CamelCasedProperties<Extract<QueryMsg, {
        module: unknown;
    }>["module"]>) => QueryMsg;
    static moduleIds: () => QueryMsg;
    static andrHook: (andromedaHook: AndromedaHook) => QueryMsg;
}
