/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Rate, Uint128, Decimal, AndrAddr, Binary, InstantiateMsg, RateInfo, Coin, PercentRate, Recipient, ExecuteMsg, ReplyOn, OwnershipMessage, Expiration, Timestamp, Uint64, Addr, Permission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, QueryMsg, AndromedaHook, Funds, Cw20Coin, BalanceResponse, BlockHeightResponse, IsOperatorResponse, KernelAddressResponse, OperatorsResponse, PublisherResponse, ContractOwnerResponse, PaymentsResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./RatesContractTs.types";
export interface RatesContractTsReadOnlyInterface {
  contractAddress: string;
  payments: () => Promise<PaymentsResponse>;
  owner: () => Promise<ContractOwnerResponse>;
  operators: () => Promise<OperatorsResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  isOperator: ({
    address
  }: {
    address: string;
  }) => Promise<IsOperatorResponse>;
  version: () => Promise<VersionResponse>;
  balance: ({
    address
  }: {
    address: AndrAddr;
  }) => Promise<BalanceResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  andrHook: (andromedaHook: AndromedaHook) => Promise<Binary>;
}
export class RatesContractTsQueryClient implements RatesContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.payments = this.payments.bind(this);
    this.owner = this.owner.bind(this);
    this.operators = this.operators.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.isOperator = this.isOperator.bind(this);
    this.version = this.version.bind(this);
    this.balance = this.balance.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.andrHook = this.andrHook.bind(this);
  }

  payments = async (): Promise<PaymentsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      payments: {}
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  operators = async (): Promise<OperatorsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operators: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  isOperator = async ({
    address
  }: {
    address: string;
  }): Promise<IsOperatorResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_operator: {
        address
      }
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  balance = async ({
    address
  }: {
    address: AndrAddr;
  }): Promise<BalanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {
        address
      }
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  andrHook = async (andromedaHook: AndromedaHook): Promise<Binary> => {
    return this.client.queryContractSmart(this.contractAddress, {
      andr_hook: andromedaHook
    });
  };
}
export interface RatesContractTsInterface {
  contractAddress: string;
  sender: string;
  updateRates: ({
    rates
  }: {
    rates: RateInfo[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setPermission: ({
    action,
    actor,
    permission
  }: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removePermission: ({
    action,
    actor
  }: {
    action: string;
    actor: AndrAddr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissionAction: ({
    action
  }: {
    action: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class RatesContractTsClient implements RatesContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateRates = this.updateRates.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.setPermission = this.setPermission.bind(this);
    this.removePermission = this.removePermission.bind(this);
    this.permissionAction = this.permissionAction.bind(this);
  }

  updateRates = async ({
    rates
  }: {
    rates: RateInfo[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_rates: {
        rates
      }
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  setPermission = async ({
    action,
    actor,
    permission
  }: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_permission: {
        action,
        actor,
        permission
      }
    }, fee, memo, _funds);
  };
  removePermission = async ({
    action,
    actor
  }: {
    action: string;
    actor: AndrAddr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_permission: {
        action,
        actor
      }
    }, fee, memo, _funds);
  };
  permissionAction = async ({
    action
  }: {
    action: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permission_action: {
        action
      }
    }, fee, memo, _funds);
  };
}