/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Asset, AndrAddr, InstantiateMsg, ExecuteMsg, Expiry, Milliseconds, Uint128, ReplyOn, Binary, OwnershipMessage, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, ConfigResponse, IsClaimedResponse, KernelAddressResponse, LatestStageResponse, MerkleRootResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, TotalClaimedResponse, TypeResponse, VersionResponse } from "./MerkleAirdropContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class MerkleAirdropContractTsExecuteMsgBuilder {
  static registerMerkleRoot = ({
    expiration,
    merkleRoot,
    totalAmount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_merkle_root: unknown;
  }>["register_merkle_root"]>): ExecuteMsg => {
    return {
      register_merkle_root: ({
        expiration,
        merkle_root: merkleRoot,
        total_amount: totalAmount
      } as const)
    };
  };
  static claim = ({
    amount,
    proof,
    stage
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim: unknown;
  }>["claim"]>): ExecuteMsg => {
    return {
      claim: ({
        amount,
        proof,
        stage
      } as const)
    };
  };
  static burn = ({
    stage
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    burn: unknown;
  }>["burn"]>): ExecuteMsg => {
    return {
      burn: ({
        stage
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class MerkleAirdropContractTsQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static merkleRoot = ({
    stage
  }: CamelCasedProperties<Extract<QueryMsg, {
    merkle_root: unknown;
  }>["merkle_root"]>): QueryMsg => {
    return {
      merkle_root: ({
        stage
      } as const)
    };
  };
  static latestStage = (): QueryMsg => {
    return {
      latest_stage: ({} as const)
    };
  };
  static isClaimed = ({
    address,
    stage
  }: CamelCasedProperties<Extract<QueryMsg, {
    is_claimed: unknown;
  }>["is_claimed"]>): QueryMsg => {
    return {
      is_claimed: ({
        address,
        stage
      } as const)
    };
  };
  static totalClaimed = ({
    stage
  }: CamelCasedProperties<Extract<QueryMsg, {
    total_claimed: unknown;
  }>["total_claimed"]>): QueryMsg => {
    return {
      total_claimed: ({
        stage
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rates: unknown;
  }>["rates"]>): QueryMsg => {
    return {
      rates: ({
        action
      } as const)
    };
  };
  static allRates = (): QueryMsg => {
    return {
      all_rates: ({} as const)
    };
  };
}