/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Milliseconds, AndrAddr, Expiry, InstantiateMsg, ExecuteMsg, Uint128, Binary, ReplyOn, OwnershipMessage, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, Cw20ReceiveMsg, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, ConfigResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, StateResponse, TypeResponse, UserInfoResponse, VersionResponse } from "./LockdropContractTs.types";
export interface LockdropContractTsReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  state: () => Promise<StateResponse>;
  userInfo: ({
    address
  }: {
    address: string;
  }) => Promise<UserInfoResponse>;
  withdrawalPercentAllowed: ({
    timestamp
  }: {
    timestamp?: Milliseconds;
  }) => Promise<Decimal>;
  owner: () => Promise<ContractOwnerResponse>;
  ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  appContract: () => Promise<AppContractResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  version: () => Promise<VersionResponse>;
  aDOBaseVersion: () => Promise<ADOBaseVersionResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  rates: ({
    action
  }: {
    action: string;
  }) => Promise<NullableRate>;
  allRates: () => Promise<AllRatesResponse>;
}
export class LockdropContractTsQueryClient implements LockdropContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.state = this.state.bind(this);
    this.userInfo = this.userInfo.bind(this);
    this.withdrawalPercentAllowed = this.withdrawalPercentAllowed.bind(this);
    this.owner = this.owner.bind(this);
    this.ownershipRequest = this.ownershipRequest.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.appContract = this.appContract.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.version = this.version.bind(this);
    this.aDOBaseVersion = this.aDOBaseVersion.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.rates = this.rates.bind(this);
    this.allRates = this.allRates.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  state = async (): Promise<StateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      state: {}
    });
  };
  userInfo = async ({
    address
  }: {
    address: string;
  }): Promise<UserInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_info: {
        address
      }
    });
  };
  withdrawalPercentAllowed = async ({
    timestamp
  }: {
    timestamp?: Milliseconds;
  }): Promise<Decimal> => {
    return this.client.queryContractSmart(this.contractAddress, {
      withdrawal_percent_allowed: {
        timestamp
      }
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  ownershipRequest = async (): Promise<ContractPotentialOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership_request: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  appContract = async (): Promise<AppContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      app_contract: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  aDOBaseVersion = async (): Promise<ADOBaseVersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      a_d_o_base_version: {}
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  rates = async ({
    action
  }: {
    action: string;
  }): Promise<NullableRate> => {
    return this.client.queryContractSmart(this.contractAddress, {
      rates: {
        action
      }
    });
  };
  allRates = async (): Promise<AllRatesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_rates: {}
    });
  };
}
export interface LockdropContractTsInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  depositNative: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawNative: ({
    amount
  }: {
    amount?: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  enableClaims: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  rates: (ratesMessage: RatesMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class LockdropContractTsClient implements LockdropContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.depositNative = this.depositNative.bind(this);
    this.withdrawNative = this.withdrawNative.bind(this);
    this.claimRewards = this.claimRewards.bind(this);
    this.enableClaims = this.enableClaims.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.permissioning = this.permissioning.bind(this);
    this.rates = this.rates.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  depositNative = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_native: {}
    }, fee, memo, _funds);
  };
  withdrawNative = async ({
    amount
  }: {
    amount?: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_native: {
        amount
      }
    }, fee, memo, _funds);
  };
  claimRewards = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_rewards: {}
    }, fee, memo, _funds);
  };
  enableClaims = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      enable_claims: {}
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  permissioning = async (permissioningMessage: PermissioningMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permissioning: permissioningMessage
    }, fee, memo, _funds);
  };
  rates = async (ratesMessage: RatesMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      rates: ratesMessage
    }, fee, memo, _funds);
  };
}