/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { AndrAddr, InstantiateMsg, ExecuteMsg, Binary, Expiration, Timestamp, Uint64, Uint128, ReplyOn, OwnershipMessage, Expiry, Milliseconds, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, TokenExtension, TransferAgreement, Coin, MintMsg, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllNftInfoResponseForTokenExtension, OwnerOfResponse, Approval, NftInfoResponseForTokenExtension, OperatorsResponse, AllRatesResponse, TokensResponse, AppContractResponse, ApprovalResponse, ApprovalsResponse, BlockHeightResponse, ContractInfoResponse, IsArchivedResponse, KernelAddressResponse, MinterResponse, NumTokensResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, NullableTransferAgreement, TypeResponse, VersionResponse } from "./Cw721ContractTs.types";
export interface Cw721ContractTsReadOnlyInterface {
  contractAddress: string;
  ownerOf: ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }) => Promise<OwnerOfResponse>;
  allOperators: ({
    includeExpired,
    limit,
    owner,
    startAfter
  }: {
    includeExpired?: boolean;
    limit?: number;
    owner: string;
    startAfter?: string;
  }) => Promise<OperatorsResponse>;
  numTokens: () => Promise<NumTokensResponse>;
  nftInfo: ({
    tokenId
  }: {
    tokenId: string;
  }) => Promise<NftInfoResponseForTokenExtension>;
  allNftInfo: ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }) => Promise<AllNftInfoResponseForTokenExtension>;
  tokens: ({
    limit,
    owner,
    startAfter
  }: {
    limit?: number;
    owner: string;
    startAfter?: string;
  }) => Promise<TokensResponse>;
  allTokens: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<TokensResponse>;
  isArchived: ({
    tokenId
  }: {
    tokenId: string;
  }) => Promise<IsArchivedResponse>;
  transferAgreement: ({
    tokenId
  }: {
    tokenId: string;
  }) => Promise<NullableTransferAgreement>;
  contractInfo: () => Promise<ContractInfoResponse>;
  minter: () => Promise<MinterResponse>;
  approval: ({
    includeExpired,
    spender,
    tokenId
  }: {
    includeExpired?: boolean;
    spender: string;
    tokenId: string;
  }) => Promise<ApprovalResponse>;
  approvals: ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }) => Promise<ApprovalsResponse>;
  owner: () => Promise<ContractOwnerResponse>;
  ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  appContract: () => Promise<AppContractResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  version: () => Promise<VersionResponse>;
  aDOBaseVersion: () => Promise<ADOBaseVersionResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  rates: ({
    action
  }: {
    action: string;
  }) => Promise<NullableRate>;
  allRates: () => Promise<AllRatesResponse>;
}
export class Cw721ContractTsQueryClient implements Cw721ContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.ownerOf = this.ownerOf.bind(this);
    this.allOperators = this.allOperators.bind(this);
    this.numTokens = this.numTokens.bind(this);
    this.nftInfo = this.nftInfo.bind(this);
    this.allNftInfo = this.allNftInfo.bind(this);
    this.tokens = this.tokens.bind(this);
    this.allTokens = this.allTokens.bind(this);
    this.isArchived = this.isArchived.bind(this);
    this.transferAgreement = this.transferAgreement.bind(this);
    this.contractInfo = this.contractInfo.bind(this);
    this.minter = this.minter.bind(this);
    this.approval = this.approval.bind(this);
    this.approvals = this.approvals.bind(this);
    this.owner = this.owner.bind(this);
    this.ownershipRequest = this.ownershipRequest.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.appContract = this.appContract.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.version = this.version.bind(this);
    this.aDOBaseVersion = this.aDOBaseVersion.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.rates = this.rates.bind(this);
    this.allRates = this.allRates.bind(this);
  }

  ownerOf = async ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }): Promise<OwnerOfResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner_of: {
        include_expired: includeExpired,
        token_id: tokenId
      }
    });
  };
  allOperators = async ({
    includeExpired,
    limit,
    owner,
    startAfter
  }: {
    includeExpired?: boolean;
    limit?: number;
    owner: string;
    startAfter?: string;
  }): Promise<OperatorsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_operators: {
        include_expired: includeExpired,
        limit,
        owner,
        start_after: startAfter
      }
    });
  };
  numTokens = async (): Promise<NumTokensResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      num_tokens: {}
    });
  };
  nftInfo = async ({
    tokenId
  }: {
    tokenId: string;
  }): Promise<NftInfoResponseForTokenExtension> => {
    return this.client.queryContractSmart(this.contractAddress, {
      nft_info: {
        token_id: tokenId
      }
    });
  };
  allNftInfo = async ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }): Promise<AllNftInfoResponseForTokenExtension> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_nft_info: {
        include_expired: includeExpired,
        token_id: tokenId
      }
    });
  };
  tokens = async ({
    limit,
    owner,
    startAfter
  }: {
    limit?: number;
    owner: string;
    startAfter?: string;
  }): Promise<TokensResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      tokens: {
        limit,
        owner,
        start_after: startAfter
      }
    });
  };
  allTokens = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<TokensResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_tokens: {
        limit,
        start_after: startAfter
      }
    });
  };
  isArchived = async ({
    tokenId
  }: {
    tokenId: string;
  }): Promise<IsArchivedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_archived: {
        token_id: tokenId
      }
    });
  };
  transferAgreement = async ({
    tokenId
  }: {
    tokenId: string;
  }): Promise<NullableTransferAgreement> => {
    return this.client.queryContractSmart(this.contractAddress, {
      transfer_agreement: {
        token_id: tokenId
      }
    });
  };
  contractInfo = async (): Promise<ContractInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      contract_info: {}
    });
  };
  minter = async (): Promise<MinterResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      minter: {}
    });
  };
  approval = async ({
    includeExpired,
    spender,
    tokenId
  }: {
    includeExpired?: boolean;
    spender: string;
    tokenId: string;
  }): Promise<ApprovalResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      approval: {
        include_expired: includeExpired,
        spender,
        token_id: tokenId
      }
    });
  };
  approvals = async ({
    includeExpired,
    tokenId
  }: {
    includeExpired?: boolean;
    tokenId: string;
  }): Promise<ApprovalsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      approvals: {
        include_expired: includeExpired,
        token_id: tokenId
      }
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  ownershipRequest = async (): Promise<ContractPotentialOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership_request: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  appContract = async (): Promise<AppContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      app_contract: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  aDOBaseVersion = async (): Promise<ADOBaseVersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      a_d_o_base_version: {}
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  rates = async ({
    action
  }: {
    action: string;
  }): Promise<NullableRate> => {
    return this.client.queryContractSmart(this.contractAddress, {
      rates: {
        action
      }
    });
  };
  allRates = async (): Promise<AllRatesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_rates: {}
    });
  };
}
export interface Cw721ContractTsInterface {
  contractAddress: string;
  sender: string;
  mint: ({
    extension,
    owner,
    tokenId,
    tokenUri
  }: {
    extension: TokenExtension;
    owner: string;
    tokenId: string;
    tokenUri?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  transferNft: ({
    recipient,
    tokenId
  }: {
    recipient: AndrAddr;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  sendNft: ({
    contract,
    msg,
    tokenId
  }: {
    contract: AndrAddr;
    msg: Binary;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  approve: ({
    expires,
    spender,
    tokenId
  }: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  revoke: ({
    spender,
    tokenId
  }: {
    spender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  approveAll: ({
    expires,
    operator
  }: {
    expires?: Expiration;
    operator: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  revokeAll: ({
    operator
  }: {
    operator: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  burn: ({
    tokenId
  }: {
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  archive: ({
    tokenId
  }: {
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  transferAgreement: ({
    agreement,
    tokenId
  }: {
    agreement?: TransferAgreement;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  batchMint: ({
    tokens
  }: {
    tokens: MintMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  rates: (ratesMessage: RatesMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class Cw721ContractTsClient implements Cw721ContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.transferNft = this.transferNft.bind(this);
    this.sendNft = this.sendNft.bind(this);
    this.approve = this.approve.bind(this);
    this.revoke = this.revoke.bind(this);
    this.approveAll = this.approveAll.bind(this);
    this.revokeAll = this.revokeAll.bind(this);
    this.burn = this.burn.bind(this);
    this.archive = this.archive.bind(this);
    this.transferAgreement = this.transferAgreement.bind(this);
    this.batchMint = this.batchMint.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.permissioning = this.permissioning.bind(this);
    this.rates = this.rates.bind(this);
  }

  mint = async ({
    extension,
    owner,
    tokenId,
    tokenUri
  }: {
    extension: TokenExtension;
    owner: string;
    tokenId: string;
    tokenUri?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint: {
        extension,
        owner,
        token_id: tokenId,
        token_uri: tokenUri
      }
    }, fee, memo, _funds);
  };
  transferNft = async ({
    recipient,
    tokenId
  }: {
    recipient: AndrAddr;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer_nft: {
        recipient,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  sendNft = async ({
    contract,
    msg,
    tokenId
  }: {
    contract: AndrAddr;
    msg: Binary;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      send_nft: {
        contract,
        msg,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  approve = async ({
    expires,
    spender,
    tokenId
  }: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      approve: {
        expires,
        spender,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  revoke = async ({
    spender,
    tokenId
  }: {
    spender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      revoke: {
        spender,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  approveAll = async ({
    expires,
    operator
  }: {
    expires?: Expiration;
    operator: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      approve_all: {
        expires,
        operator
      }
    }, fee, memo, _funds);
  };
  revokeAll = async ({
    operator
  }: {
    operator: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      revoke_all: {
        operator
      }
    }, fee, memo, _funds);
  };
  burn = async ({
    tokenId
  }: {
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      burn: {
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  archive = async ({
    tokenId
  }: {
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      archive: {
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  transferAgreement = async ({
    agreement,
    tokenId
  }: {
    agreement?: TransferAgreement;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer_agreement: {
        agreement,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  batchMint = async ({
    tokens
  }: {
    tokens: MintMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      batch_mint: {
        tokens
      }
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  permissioning = async (permissioningMessage: PermissioningMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permissioning: permissioningMessage
    }, fee, memo, _funds);
  };
  rates = async (ratesMessage: RatesMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      rates: ratesMessage
    }, fee, memo, _funds);
  };
}