/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Milliseconds, AddressPercent, OwnershipMessage, Addr, PermissioningMessage, AMPCtx, AMPMsg, Coin, AppContractResponse, BlockHeightResponse, GetSplitterConfigResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, TypeResponse, VersionResponse } from "./CrossChainSwapContractTs.types";
export interface CrossChainSwapContractTsReadOnlyInterface {
    contractAddress: string;
    getSplitterConfig: () => Promise<GetSplitterConfigResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export declare class CrossChainSwapContractTsQueryClient implements CrossChainSwapContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    getSplitterConfig: () => Promise<GetSplitterConfigResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export interface CrossChainSwapContractTsInterface {
    contractAddress: string;
    sender: string;
    updateRecipients: ({ recipients }: {
        recipients: AddressPercent[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateLock: ({ lockTime }: {
        lockTime: Milliseconds;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    send: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class CrossChainSwapContractTsClient implements CrossChainSwapContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    updateRecipients: ({ recipients }: {
        recipients: AddressPercent[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateLock: ({ lockTime }: {
        lockTime: Milliseconds;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    send: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
