/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Milliseconds, AndrAddr, Expiry, InstantiateMsg, ExecuteMsg, Uint128, Binary, ReplyOn, OwnershipMessage, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, Cw20ReceiveMsg, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, ConfigResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, StateResponse, TypeResponse, UserInfoResponse, VersionResponse } from "./LockdropContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class LockdropContractTsExecuteMsgBuilder {
  static receive = ({
    amount,
    msg,
    sender
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    receive: unknown;
  }>["receive"]>): ExecuteMsg => {
    return {
      receive: ({
        amount,
        msg,
        sender
      } as const)
    };
  };
  static depositNative = (): ExecuteMsg => {
    return {
      deposit_native: ({} as const)
    };
  };
  static withdrawNative = ({
    amount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw_native: unknown;
  }>["withdraw_native"]>): ExecuteMsg => {
    return {
      withdraw_native: ({
        amount
      } as const)
    };
  };
  static claimRewards = (): ExecuteMsg => {
    return {
      claim_rewards: ({} as const)
    };
  };
  static enableClaims = (): ExecuteMsg => {
    return {
      enable_claims: ({} as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class LockdropContractTsQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static state = (): QueryMsg => {
    return {
      state: ({} as const)
    };
  };
  static userInfo = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    user_info: unknown;
  }>["user_info"]>): QueryMsg => {
    return {
      user_info: ({
        address
      } as const)
    };
  };
  static withdrawalPercentAllowed = ({
    timestamp
  }: CamelCasedProperties<Extract<QueryMsg, {
    withdrawal_percent_allowed: unknown;
  }>["withdrawal_percent_allowed"]>): QueryMsg => {
    return {
      withdrawal_percent_allowed: ({
        timestamp
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rates: unknown;
  }>["rates"]>): QueryMsg => {
    return {
      rates: ({
        action
      } as const)
    };
  };
  static allRates = (): QueryMsg => {
    return {
      all_rates: ({} as const)
    };
  };
}