/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
/// <reference types="./global.d.ts" />
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { OwnershipMessage, Uint64, ActionFee, ADOMetadata, NullableActionFee, IsUnpublishedCodeIdResponse, KernelAddressResponse, ContractOwnerResponse, TypeResponse, VersionResponse } from "./AdodbContractTs.types";
export interface AdodbContractTsReadOnlyInterface {
    contractAddress: string;
    codeId: ({ key }: {
        key: string;
    }) => Promise<Uint64>;
    isUnpublishedCodeId: ({ codeId }: {
        codeId: number;
    }) => Promise<IsUnpublishedCodeIdResponse>;
    adoType: ({ codeId }: {
        codeId: number;
    }) => Promise<AdoTypeResponse>;
    allAdoTypes: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<AllAdoTypesResponse>;
    adoVersions: ({ adoType, limit, startAfter }: {
        adoType: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<AdoVersionsResponse>;
    adoMetadata: ({ adoType }: {
        adoType: string;
    }) => Promise<ADOMetadata>;
    actionFee: ({ action, adoType }: {
        action: string;
        adoType: string;
    }) => Promise<NullableActionFee>;
    actionFeeByCodeId: ({ action, codeId }: {
        action: string;
        codeId: number;
    }) => Promise<NullableActionFee>;
    version: () => Promise<VersionResponse>;
    type: () => Promise<TypeResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
}
export declare class AdodbContractTsQueryClient implements AdodbContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    codeId: ({ key }: {
        key: string;
    }) => Promise<Uint64>;
    isUnpublishedCodeId: ({ codeId }: {
        codeId: number;
    }) => Promise<IsUnpublishedCodeIdResponse>;
    adoType: ({ codeId }: {
        codeId: number;
    }) => Promise<AdoTypeResponse>;
    allAdoTypes: ({ limit, startAfter }: {
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<AllAdoTypesResponse>;
    adoVersions: ({ adoType, limit, startAfter }: {
        adoType: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<AdoVersionsResponse>;
    adoMetadata: ({ adoType }: {
        adoType: string;
    }) => Promise<ADOMetadata>;
    actionFee: ({ action, adoType }: {
        action: string;
        adoType: string;
    }) => Promise<NullableActionFee>;
    actionFeeByCodeId: ({ action, codeId }: {
        action: string;
        codeId: number;
    }) => Promise<NullableActionFee>;
    version: () => Promise<VersionResponse>;
    type: () => Promise<TypeResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
}
export interface AdodbContractTsInterface {
    contractAddress: string;
    sender: string;
    publish: ({ actionFees, adoType, codeId, publisher, version }: {
        actionFees?: ActionFee[];
        adoType: string;
        codeId: number;
        publisher?: string;
        version: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    unpublish: ({ adoType, version }: {
        adoType: string;
        version: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateActionFees: ({ actionFees, adoType }: {
        actionFees: ActionFee[];
        adoType: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    removeActionFees: ({ actions, adoType }: {
        actions: string[];
        adoType: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updatePublisher: ({ adoType, publisher }: {
        adoType: string;
        publisher: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class AdodbContractTsClient implements AdodbContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    publish: ({ actionFees, adoType, codeId, publisher, version }: {
        actionFees?: ActionFee[] | undefined;
        adoType: string;
        codeId: number;
        publisher?: string | undefined;
        version: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    unpublish: ({ adoType, version }: {
        adoType: string;
        version: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateActionFees: ({ actionFees, adoType }: {
        actionFees: ActionFee[];
        adoType: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    removeActionFees: ({ actions, adoType }: {
        actions: string[];
        adoType: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updatePublisher: ({ adoType, publisher }: {
        adoType: string;
        publisher: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
