/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, QueryMsg } from "./AdodbContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class AdodbContractTsExecuteMsgBuilder {
    static publish: ({ actionFees, adoType, codeId, publisher, version }: CamelCasedProperties<Extract<ExecuteMsg, {
        publish: unknown;
    }>["publish"]>) => ExecuteMsg;
    static unpublish: ({ adoType, version }: CamelCasedProperties<Extract<ExecuteMsg, {
        unpublish: unknown;
    }>["unpublish"]>) => ExecuteMsg;
    static updateActionFees: ({ actionFees, adoType }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_action_fees: unknown;
    }>["update_action_fees"]>) => ExecuteMsg;
    static removeActionFees: ({ actions, adoType }: CamelCasedProperties<Extract<ExecuteMsg, {
        remove_action_fees: unknown;
    }>["remove_action_fees"]>) => ExecuteMsg;
    static updatePublisher: ({ adoType, publisher }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_publisher: unknown;
    }>["update_publisher"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
}
export declare abstract class AdodbContractTsQueryMsgBuilder {
    static codeId: ({ key }: CamelCasedProperties<Extract<QueryMsg, {
        code_id: unknown;
    }>["code_id"]>) => QueryMsg;
    static isUnpublishedCodeId: ({ codeId }: CamelCasedProperties<Extract<QueryMsg, {
        is_unpublished_code_id: unknown;
    }>["is_unpublished_code_id"]>) => QueryMsg;
    static adoType: ({ codeId }: CamelCasedProperties<Extract<QueryMsg, {
        ado_type: unknown;
    }>["ado_type"]>) => QueryMsg;
    static allAdoTypes: ({ limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        all_ado_types: unknown;
    }>["all_ado_types"]>) => QueryMsg;
    static adoVersions: ({ adoType, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        ado_versions: unknown;
    }>["ado_versions"]>) => QueryMsg;
    static adoMetadata: ({ adoType }: CamelCasedProperties<Extract<QueryMsg, {
        ado_metadata: unknown;
    }>["ado_metadata"]>) => QueryMsg;
    static actionFee: ({ action, adoType }: CamelCasedProperties<Extract<QueryMsg, {
        action_fee: unknown;
    }>["action_fee"]>) => QueryMsg;
    static actionFeeByCodeId: ({ action, codeId }: CamelCasedProperties<Extract<QueryMsg, {
        action_fee_by_code_id: unknown;
    }>["action_fee_by_code_id"]>) => QueryMsg;
    static version: () => QueryMsg;
    static type: () => QueryMsg;
    static owner: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
}
