/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, Binary, Duration, InstantiateMsg, Module, Recipient, ExecuteMsg, WithdrawalType, Uint128, Decimal, VoteOption, ReplyOn, OwnershipMessage, Expiration, Timestamp, Uint64, Addr, Permission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, BalanceResponse, BatchResponse, ArrayOfBatchResponse, BlockHeightResponse, Config, IsOperatorResponse, KernelAddressResponse, OperatorsResponse, PublisherResponse, ContractOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./VestingContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class VestingContractTsExecuteMsgBuilder {
  static claim = ({
    batchId,
    numberOfClaims
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim: unknown;
  }>["claim"]>): ExecuteMsg => {
    return {
      claim: ({
        batch_id: batchId,
        number_of_claims: numberOfClaims
      } as const)
    };
  };
  static claimAll = ({
    limit,
    upToTime
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim_all: unknown;
  }>["claim_all"]>): ExecuteMsg => {
    return {
      claim_all: ({
        limit,
        up_to_time: upToTime
      } as const)
    };
  };
  static createBatch = ({
    lockupDuration,
    releaseAmount,
    releaseUnit,
    validatorToDelegateTo
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    create_batch: unknown;
  }>["create_batch"]>): ExecuteMsg => {
    return {
      create_batch: ({
        lockup_duration: lockupDuration,
        release_amount: releaseAmount,
        release_unit: releaseUnit,
        validator_to_delegate_to: validatorToDelegateTo
      } as const)
    };
  };
  static delegate = ({
    amount,
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    delegate: unknown;
  }>["delegate"]>): ExecuteMsg => {
    return {
      delegate: ({
        amount,
        validator
      } as const)
    };
  };
  static redelegate = ({
    amount,
    from,
    to
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    redelegate: unknown;
  }>["redelegate"]>): ExecuteMsg => {
    return {
      redelegate: ({
        amount,
        from,
        to
      } as const)
    };
  };
  static undelegate = ({
    amount,
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    undelegate: unknown;
  }>["undelegate"]>): ExecuteMsg => {
    return {
      undelegate: ({
        amount,
        validator
      } as const)
    };
  };
  static withdrawRewards = (): ExecuteMsg => {
    return {
      withdraw_rewards: ({} as const)
    };
  };
  static vote = ({
    proposalId,
    vote
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    vote: unknown;
  }>["vote"]>): ExecuteMsg => {
    return {
      vote: ({
        proposal_id: proposalId,
        vote
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static setPermission = ({
    action,
    actor,
    permission
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    set_permission: unknown;
  }>["set_permission"]>): ExecuteMsg => {
    return {
      set_permission: ({
        action,
        actor,
        permission
      } as const)
    };
  };
  static removePermission = ({
    action,
    actor
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    remove_permission: unknown;
  }>["remove_permission"]>): ExecuteMsg => {
    return {
      remove_permission: ({
        action,
        actor
      } as const)
    };
  };
  static permissionAction = ({
    action
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    permission_action: unknown;
  }>["permission_action"]>): ExecuteMsg => {
    return {
      permission_action: ({
        action
      } as const)
    };
  };
}
export abstract class VestingContractTsQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static batch = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    batch: unknown;
  }>["batch"]>): QueryMsg => {
    return {
      batch: ({
        id
      } as const)
    };
  };
  static batches = ({
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    batches: unknown;
  }>["batches"]>): QueryMsg => {
    return {
      batches: ({
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static operators = (): QueryMsg => {
    return {
      operators: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static isOperator = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    is_operator: unknown;
  }>["is_operator"]>): QueryMsg => {
    return {
      is_operator: ({
        address
      } as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static balance = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    balance: unknown;
  }>["balance"]>): QueryMsg => {
    return {
      balance: ({
        address
      } as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
}