/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, InstantiateMsg, Module, ExecuteMsg, EscrowCondition, Milliseconds, Uint128, Binary, ReplyOn, OwnershipMessage, Addr, PermissioningMessage, Permission, Uint64, Coin, Recipient, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, QueryMsg, AndromedaHook, Funds, Cw20Coin, AppContractResponse, BlockHeightResponse, GetLockedFundsResponse, Escrow, GetLockedFundsForRecipientResponse, KernelAddressResponse, ArrayOfString, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./TimelockContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class TimelockContractTsExecuteMsgBuilder {
  static holdFunds = ({
    condition,
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    hold_funds: unknown;
  }>["hold_funds"]>): ExecuteMsg => {
    return {
      hold_funds: ({
        condition,
        recipient
      } as const)
    };
  };
  static releaseFunds = ({
    limit,
    recipientAddr,
    startAfter
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    release_funds: unknown;
  }>["release_funds"]>): ExecuteMsg => {
    return {
      release_funds: ({
        limit,
        recipient_addr: recipientAddr,
        start_after: startAfter
      } as const)
    };
  };
  static releaseSpecificFunds = ({
    owner,
    recipientAddr
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    release_specific_funds: unknown;
  }>["release_specific_funds"]>): ExecuteMsg => {
    return {
      release_specific_funds: ({
        owner,
        recipient_addr: recipientAddr
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static registerModule = ({
    module
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_module: unknown;
  }>["register_module"]>): ExecuteMsg => {
    return {
      register_module: ({
        module
      } as const)
    };
  };
  static deregisterModule = ({
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deregister_module: unknown;
  }>["deregister_module"]>): ExecuteMsg => {
    return {
      deregister_module: ({
        module_idx: moduleIdx
      } as const)
    };
  };
  static alterModule = ({
    module,
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    alter_module: unknown;
  }>["alter_module"]>): ExecuteMsg => {
    return {
      alter_module: ({
        module,
        module_idx: moduleIdx
      } as const)
    };
  };
}
export abstract class TimelockContractTsQueryMsgBuilder {
  static getLockedFunds = ({
    owner,
    recipient
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_locked_funds: unknown;
  }>["get_locked_funds"]>): QueryMsg => {
    return {
      get_locked_funds: ({
        owner,
        recipient
      } as const)
    };
  };
  static getLockedFundsForRecipient = ({
    limit,
    recipient,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_locked_funds_for_recipient: unknown;
  }>["get_locked_funds_for_recipient"]>): QueryMsg => {
    return {
      get_locked_funds_for_recipient: ({
        limit,
        recipient,
        start_after: startAfter
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static module = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    module: unknown;
  }>["module"]>): QueryMsg => {
    return {
      module: ({
        id
      } as const)
    };
  };
  static moduleIds = (): QueryMsg => {
    return {
      module_ids: ({} as const)
    };
  };
  static andrHook = (andromedaHook: AndromedaHook): QueryMsg => {
    return {
      andr_hook: andromedaHook
    };
  };
}