/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { WithdrawalType, Uint128, VoteOption, OwnershipMessage, Addr, PermissioningMessage, AMPCtx, AMPMsg, Coin, AppContractResponse, BatchResponse, ArrayOfBatchResponse, BlockHeightResponse, Config, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, TypeResponse, VersionResponse } from "./VestingContractTs.types";
export interface VestingContractTsReadOnlyInterface {
    contractAddress: string;
    config: () => Promise<Config>;
    batch: ({ id }: {
        id: number;
    }) => Promise<BatchResponse>;
    batches: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: number;
    }) => Promise<ArrayOfBatchResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export declare class VestingContractTsQueryClient implements VestingContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    config: () => Promise<Config>;
    batch: ({ id }: {
        id: number;
    }) => Promise<BatchResponse>;
    batches: ({ limit, startAfter }: {
        limit?: number | undefined;
        startAfter?: number | undefined;
    }) => Promise<ArrayOfBatchResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export interface VestingContractTsInterface {
    contractAddress: string;
    sender: string;
    claim: ({ batchId, numberOfClaims }: {
        batchId: number;
        numberOfClaims?: number;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    claimAll: ({ limit, upToTime }: {
        limit?: number;
        upToTime?: number;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    createBatch: ({ lockupDuration, releaseAmount, releaseUnit, validatorToDelegateTo }: {
        lockupDuration?: number;
        releaseAmount: WithdrawalType;
        releaseUnit: number;
        validatorToDelegateTo?: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    delegate: ({ amount, validator }: {
        amount?: Uint128;
        validator: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    redelegate: ({ amount, from, to }: {
        amount?: Uint128;
        from: string;
        to: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    undelegate: ({ amount, validator }: {
        amount?: Uint128;
        validator: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdrawRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    vote: ({ proposalId, vote }: {
        proposalId: number;
        vote: VoteOption;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class VestingContractTsClient implements VestingContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    claim: ({ batchId, numberOfClaims }: {
        batchId: number;
        numberOfClaims?: number | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    claimAll: ({ limit, upToTime }: {
        limit?: number | undefined;
        upToTime?: number | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    createBatch: ({ lockupDuration, releaseAmount, releaseUnit, validatorToDelegateTo }: {
        lockupDuration?: number | undefined;
        releaseAmount: WithdrawalType;
        releaseUnit: number;
        validatorToDelegateTo?: string | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    delegate: ({ amount, validator }: {
        amount?: string | undefined;
        validator: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    redelegate: ({ amount, from, to }: {
        amount?: string | undefined;
        from: string;
        to: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    undelegate: ({ amount, validator }: {
        amount?: string | undefined;
        validator: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    withdrawRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    vote: ({ proposalId, vote }: {
        proposalId: number;
        vote: VoteOption;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
