/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  kernel_address: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  add_path: {
    address: Addr;
    name: string;
    parent_address?: AndrAddr | null;
  };
} | {
  add_symlink: {
    name: string;
    parent_address?: AndrAddr | null;
    symlink: AndrAddr;
  };
} | {
  add_parent_path: {
    name: string;
    parent_address: AndrAddr;
  };
} | {
  register_user: {
    address?: Addr | null;
    username: string;
  };
} | {
  register_library: {
    lib_address: Addr;
    lib_name: string;
  };
} | {
  register_user_cross_chain: {
    address: string;
    chain: string;
  };
};
export type Addr = string;
export type AndrAddr = string;
export type QueryMsg = {
  resolve_path: {
    path: AndrAddr;
  };
} | {
  sub_dir: {
    path: AndrAddr;
  };
} | {
  paths: {
    addr: Addr;
  };
} | {
  get_username: {
    address: Addr;
  };
} | {
  get_library: {
    address: Addr;
  };
} | {
  resolve_symlink: {
    path: AndrAddr;
  };
};
export type String = string;
export type ArrayOfString = string[];
export type ArrayOfPathDetails = PathDetails[];
export interface PathDetails {
  address: Addr;
  name: string;
}
export type VfsContractTsExecuteMsg = ExecuteMsg;