/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  kernel_address: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  deposit: {
    address?: AndrAddr | null;
  };
} | {
  pay_fee: {
    action: string;
    payee: Addr;
  };
} | {
  withdraw: {
    amount?: Uint128 | null;
    asset: string;
  };
} | {
  withdraw_cw20: {
    amount?: Uint128 | null;
    asset: string;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  ownership: OwnershipMessage;
};
export type AndrAddr = string;
export type Addr = string;
export type Uint128 = string;
export type Binary = string;
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Expiry | null;
    new_owner: Addr;
  };
};
export type Expiry = {
  from_now: Milliseconds;
} | {
  at_time: Milliseconds;
};
export type Milliseconds = number;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  balance: {
    address: AndrAddr;
    asset: string;
  };
} | {
  version: {};
} | {
  type: {};
} | {
  owner: {};
} | {
  kernel_address: {};
};
export interface BalanceResponse {
  balance: Uint128;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface TypeResponse {
  ado_type: string;
}
export interface VersionResponse {
  version: string;
}
export type EconomicsContractTsExecuteMsg = ExecuteMsg;