/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, AndrAddr, Addr, Uint128, Binary, OwnershipMessage, Expiry, Milliseconds, Cw20ReceiveMsg, QueryMsg, BalanceResponse, KernelAddressResponse, ContractOwnerResponse, TypeResponse, VersionResponse } from "./EconomicsContractTs.types";
export interface EconomicsContractTsReadOnlyInterface {
  contractAddress: string;
  balance: ({
    address,
    asset
  }: {
    address: AndrAddr;
    asset: string;
  }) => Promise<BalanceResponse>;
  version: () => Promise<VersionResponse>;
  type: () => Promise<TypeResponse>;
  owner: () => Promise<ContractOwnerResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
}
export class EconomicsContractTsQueryClient implements EconomicsContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.balance = this.balance.bind(this);
    this.version = this.version.bind(this);
    this.type = this.type.bind(this);
    this.owner = this.owner.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
  }

  balance = async ({
    address,
    asset
  }: {
    address: AndrAddr;
    asset: string;
  }): Promise<BalanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {
        address,
        asset
      }
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
}
export interface EconomicsContractTsInterface {
  contractAddress: string;
  sender: string;
  deposit: ({
    address
  }: {
    address?: AndrAddr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  payFee: ({
    action,
    payee
  }: {
    action: string;
    payee: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    amount,
    asset
  }: {
    amount?: Uint128;
    asset: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawCw20: ({
    amount,
    asset
  }: {
    amount?: Uint128;
    asset: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class EconomicsContractTsClient implements EconomicsContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposit = this.deposit.bind(this);
    this.payFee = this.payFee.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.withdrawCw20 = this.withdrawCw20.bind(this);
    this.receive = this.receive.bind(this);
    this.ownership = this.ownership.bind(this);
  }

  deposit = async ({
    address
  }: {
    address?: AndrAddr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit: {
        address
      }
    }, fee, memo, _funds);
  };
  payFee = async ({
    action,
    payee
  }: {
    action: string;
    payee: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pay_fee: {
        action,
        payee
      }
    }, fee, memo, _funds);
  };
  withdraw = async ({
    amount,
    asset
  }: {
    amount?: Uint128;
    asset: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        amount,
        asset
      }
    }, fee, memo, _funds);
  };
  withdrawCw20 = async ({
    amount,
    asset
  }: {
    amount?: Uint128;
    asset: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_cw20: {
        amount,
        asset
      }
    }, fee, memo, _funds);
  };
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
}