/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CounterRestriction, InstantiateMsg, State, ExecuteMsg, AndrAddr, ReplyOn, Uint128, Binary, OwnershipMessage, Expiry, Milliseconds, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, GetCurrentAmountResponse, GetDecreaseAmountResponse, GetIncreaseAmountResponse, GetInitialAmountResponse, GetRestrictionResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, TypeResponse, VersionResponse } from "./CounterContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class CounterContractTsExecuteMsgBuilder {
  static increment = (): ExecuteMsg => {
    return {
      increment: ({} as const)
    };
  };
  static decrement = (): ExecuteMsg => {
    return {
      decrement: ({} as const)
    };
  };
  static reset = (): ExecuteMsg => {
    return {
      reset: ({} as const)
    };
  };
  static updateRestriction = ({
    restriction
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_restriction: unknown;
  }>["update_restriction"]>): ExecuteMsg => {
    return {
      update_restriction: ({
        restriction
      } as const)
    };
  };
  static setIncreaseAmount = ({
    increaseAmount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    set_increase_amount: unknown;
  }>["set_increase_amount"]>): ExecuteMsg => {
    return {
      set_increase_amount: ({
        increase_amount: increaseAmount
      } as const)
    };
  };
  static setDecreaseAmount = ({
    decreaseAmount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    set_decrease_amount: unknown;
  }>["set_decrease_amount"]>): ExecuteMsg => {
    return {
      set_decrease_amount: ({
        decrease_amount: decreaseAmount
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class CounterContractTsQueryMsgBuilder {
  static getInitialAmount = (): QueryMsg => {
    return {
      get_initial_amount: ({} as const)
    };
  };
  static getCurrentAmount = (): QueryMsg => {
    return {
      get_current_amount: ({} as const)
    };
  };
  static getIncreaseAmount = (): QueryMsg => {
    return {
      get_increase_amount: ({} as const)
    };
  };
  static getDecreaseAmount = (): QueryMsg => {
    return {
      get_decrease_amount: ({} as const)
    };
  };
  static getRestriction = (): QueryMsg => {
    return {
      get_restriction: ({} as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rates: unknown;
  }>["rates"]>): QueryMsg => {
    return {
      rates: ({
        action
      } as const)
    };
  };
  static allRates = (): QueryMsg => {
    return {
      all_rates: ({} as const)
    };
  };
}