/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg, AndromedaHook } from "./Cw20StakingContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class Cw20StakingContractTsExecuteMsgBuilder {
    static receive: ({ amount, msg, sender }: CamelCasedProperties<Extract<ExecuteMsg, {
        receive: unknown;
    }>["receive"]>) => ExecuteMsg;
    static addRewardToken: ({ rewardToken }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_reward_token: unknown;
    }>["add_reward_token"]>) => ExecuteMsg;
    static unstakeTokens: ({ amount }: CamelCasedProperties<Extract<ExecuteMsg, {
        unstake_tokens: unknown;
    }>["unstake_tokens"]>) => ExecuteMsg;
    static claimRewards: () => ExecuteMsg;
    static updateGlobalIndexes: ({ assetInfos }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_global_indexes: unknown;
    }>["update_global_indexes"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
    static registerModule: ({ module }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_module: unknown;
    }>["register_module"]>) => ExecuteMsg;
    static deregisterModule: ({ moduleIdx }: CamelCasedProperties<Extract<ExecuteMsg, {
        deregister_module: unknown;
    }>["deregister_module"]>) => ExecuteMsg;
    static alterModule: ({ module, moduleIdx }: CamelCasedProperties<Extract<ExecuteMsg, {
        alter_module: unknown;
    }>["alter_module"]>) => ExecuteMsg;
}
export declare abstract class Cw20StakingContractTsQueryMsgBuilder {
    static config: () => QueryMsg;
    static state: () => QueryMsg;
    static staker: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        staker: unknown;
    }>["staker"]>) => QueryMsg;
    static stakers: ({ limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        stakers: unknown;
    }>["stakers"]>) => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
    static module: ({ id }: CamelCasedProperties<Extract<QueryMsg, {
        module: unknown;
    }>["module"]>) => QueryMsg;
    static moduleIds: () => QueryMsg;
    static andrHook: (andromedaHook: AndromedaHook) => QueryMsg;
}
