/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, InstantiateMsg, ExecuteMsg, Binary, Uint128, Asset, ReplyOn, OwnershipMessage, Expiry, Milliseconds, Addr, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, Cw721ReceiveMsg, Cw20ReceiveMsg, Recipient, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, PercentRate, QueryMsg, RatesQueryMessage, ADOBaseVersionResponse, AppContractResponse, BlockHeightResponse, KernelAddressResponse, Expiration, Timestamp, Uint64, Status, SaleStateResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, SaleIdsResponse, ArrayOfSaleInfo, SaleInfo, TypeResponse, VersionResponse } from "./MarketplaceContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class MarketplaceContractTsExecuteMsgBuilder {
  static receiveNft = ({
    msg,
    sender,
    tokenId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    receive_nft: unknown;
  }>["receive_nft"]>): ExecuteMsg => {
    return {
      receive_nft: ({
        msg,
        sender,
        token_id: tokenId
      } as const)
    };
  };
  static receive = ({
    amount,
    msg,
    sender
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    receive: unknown;
  }>["receive"]>): ExecuteMsg => {
    return {
      receive: ({
        amount,
        msg,
        sender
      } as const)
    };
  };
  static buy = ({
    tokenAddress,
    tokenId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    buy: unknown;
  }>["buy"]>): ExecuteMsg => {
    return {
      buy: ({
        token_address: tokenAddress,
        token_id: tokenId
      } as const)
    };
  };
  static updateSale = ({
    coinDenom,
    price,
    recipient,
    tokenAddress,
    tokenId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_sale: unknown;
  }>["update_sale"]>): ExecuteMsg => {
    return {
      update_sale: ({
        coin_denom: coinDenom,
        price,
        recipient,
        token_address: tokenAddress,
        token_id: tokenId
      } as const)
    };
  };
  static cancelSale = ({
    tokenAddress,
    tokenId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    cancel_sale: unknown;
  }>["cancel_sale"]>): ExecuteMsg => {
    return {
      cancel_sale: ({
        token_address: tokenAddress,
        token_id: tokenId
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class MarketplaceContractTsQueryMsgBuilder {
  static latestSaleState = ({
    tokenAddress,
    tokenId
  }: CamelCasedProperties<Extract<QueryMsg, {
    latest_sale_state: unknown;
  }>["latest_sale_state"]>): QueryMsg => {
    return {
      latest_sale_state: ({
        token_address: tokenAddress,
        token_id: tokenId
      } as const)
    };
  };
  static saleState = ({
    saleId
  }: CamelCasedProperties<Extract<QueryMsg, {
    sale_state: unknown;
  }>["sale_state"]>): QueryMsg => {
    return {
      sale_state: ({
        sale_id: saleId
      } as const)
    };
  };
  static saleIds = ({
    tokenAddress,
    tokenId
  }: CamelCasedProperties<Extract<QueryMsg, {
    sale_ids: unknown;
  }>["sale_ids"]>): QueryMsg => {
    return {
      sale_ids: ({
        token_address: tokenAddress,
        token_id: tokenId
      } as const)
    };
  };
  static saleInfosForAddress = ({
    limit,
    startAfter,
    tokenAddress
  }: CamelCasedProperties<Extract<QueryMsg, {
    sale_infos_for_address: unknown;
  }>["sale_infos_for_address"]>): QueryMsg => {
    return {
      sale_infos_for_address: ({
        limit,
        start_after: startAfter,
        token_address: tokenAddress
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = (ratesQueryMessage: RatesQueryMessage): QueryMsg => {
    return {
      rates: ratesQueryMessage
    };
  };
}