/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ComponentType, Binary, AndrAddr, InstantiateMsg, AppComponent, CrossChainComponent, ChainInfo, ExecuteMsg, ReplyOn, Uint128, OwnershipMessage, Expiration, Timestamp, Uint64, Addr, PermissioningMessage, Permission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, BalanceResponse, BlockHeightResponse, Boolean, ConfigResponse, String, ArrayOfAppComponent, IsOperatorResponse, KernelAddressResponse, OperatorsResponse, PublisherResponse, ContractOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./AppContractContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class AppContractContractTsExecuteMsgBuilder {
  static addAppComponent = ({
    component
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    add_app_component: unknown;
  }>["add_app_component"]>): ExecuteMsg => {
    return {
      add_app_component: ({
        component
      } as const)
    };
  };
  static claimOwnership = ({
    name,
    newOwner
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim_ownership: unknown;
  }>["claim_ownership"]>): ExecuteMsg => {
    return {
      claim_ownership: ({
        name,
        new_owner: newOwner
      } as const)
    };
  };
  static proxyMessage = ({
    msg,
    name
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    proxy_message: unknown;
  }>["proxy_message"]>): ExecuteMsg => {
    return {
      proxy_message: ({
        msg,
        name
      } as const)
    };
  };
  static updateAddress = ({
    addr,
    name
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_address: unknown;
  }>["update_address"]>): ExecuteMsg => {
    return {
      update_address: ({
        addr,
        name
      } as const)
    };
  };
  static assignAppToComponents = (): ExecuteMsg => {
    return {
      assign_app_to_components: ({} as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
}
export abstract class AppContractContractTsQueryMsgBuilder {
  static getAddress = ({
    name
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_address: unknown;
  }>["get_address"]>): QueryMsg => {
    return {
      get_address: ({
        name
      } as const)
    };
  };
  static getComponents = (): QueryMsg => {
    return {
      get_components: ({} as const)
    };
  };
  static componentExists = ({
    name
  }: CamelCasedProperties<Extract<QueryMsg, {
    component_exists: unknown;
  }>["component_exists"]>): QueryMsg => {
    return {
      component_exists: ({
        name
      } as const)
    };
  };
  static getAddressesWithNames = (): QueryMsg => {
    return {
      get_addresses_with_names: ({} as const)
    };
  };
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static operators = (): QueryMsg => {
    return {
      operators: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static isOperator = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    is_operator: unknown;
  }>["is_operator"]>): QueryMsg => {
    return {
      is_operator: ({
        address
      } as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static balance = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    balance: unknown;
  }>["balance"]>): QueryMsg => {
    return {
      balance: ({
        address
      } as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
}