/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg } from "./VaultContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class VaultContractTsExecuteMsgBuilder {
    static withdrawVault: ({ recipient, strategy, withdrawals }: CamelCasedProperties<Extract<ExecuteMsg, {
        withdraw_vault: unknown;
    }>["withdraw_vault"]>) => ExecuteMsg;
    static updateStrategy: ({ address, strategy }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_strategy: unknown;
    }>["update_strategy"]>) => ExecuteMsg;
    static withdraw: ({ recipient, tokensToWithdraw }: CamelCasedProperties<Extract<ExecuteMsg, {
        withdraw: unknown;
    }>["withdraw"]>) => ExecuteMsg;
    static deposit: ({ msg, recipient }: CamelCasedProperties<Extract<ExecuteMsg, {
        deposit: unknown;
    }>["deposit"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
}
export declare abstract class VaultContractTsQueryMsgBuilder {
    static vaultBalance: ({ address, denom, strategy }: CamelCasedProperties<Extract<QueryMsg, {
        vault_balance: unknown;
    }>["vault_balance"]>) => QueryMsg;
    static strategyAddress: ({ strategy }: CamelCasedProperties<Extract<QueryMsg, {
        strategy_address: unknown;
    }>["strategy_address"]>) => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
}
