/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Uint128, Decimal, AssetInfoBaseForString, AndrAddr, InstantiateMsg, RewardTokenUnchecked, AllocationConfig, Module, ExecuteMsg, Binary, ReplyOn, OwnershipMessage, Expiration, Timestamp, Uint64, Addr, PermissioningMessage, Permission, Cw20ReceiveMsg, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, BalanceResponse, BlockHeightResponse, Config, IsOperatorResponse, KernelAddressResponse, ArrayOfString, OperatorsResponse, PublisherResponse, ContractOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, StakerResponse, ArrayOfStakerResponse, State, TypeResponse, VersionResponse } from "./Cw20StakingContractTs.types";
export interface Cw20StakingContractTsReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  state: () => Promise<State>;
  staker: ({
    address
  }: {
    address: string;
  }) => Promise<StakerResponse>;
  stakers: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfStakerResponse>;
  timestamp: () => Promise<Uint64>;
  owner: () => Promise<ContractOwnerResponse>;
  operators: () => Promise<OperatorsResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  isOperator: ({
    address
  }: {
    address: string;
  }) => Promise<IsOperatorResponse>;
  version: () => Promise<VersionResponse>;
  balance: ({
    address
  }: {
    address: AndrAddr;
  }) => Promise<BalanceResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  module: ({
    id
  }: {
    id: Uint64;
  }) => Promise<Module>;
  moduleIds: () => Promise<ArrayOfString>;
}
export class Cw20StakingContractTsQueryClient implements Cw20StakingContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.state = this.state.bind(this);
    this.staker = this.staker.bind(this);
    this.stakers = this.stakers.bind(this);
    this.timestamp = this.timestamp.bind(this);
    this.owner = this.owner.bind(this);
    this.operators = this.operators.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.isOperator = this.isOperator.bind(this);
    this.version = this.version.bind(this);
    this.balance = this.balance.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.module = this.module.bind(this);
    this.moduleIds = this.moduleIds.bind(this);
  }

  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  state = async (): Promise<State> => {
    return this.client.queryContractSmart(this.contractAddress, {
      state: {}
    });
  };
  staker = async ({
    address
  }: {
    address: string;
  }): Promise<StakerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      staker: {
        address
      }
    });
  };
  stakers = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfStakerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      stakers: {
        limit,
        start_after: startAfter
      }
    });
  };
  timestamp = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      timestamp: {}
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  operators = async (): Promise<OperatorsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      operators: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  isOperator = async ({
    address
  }: {
    address: string;
  }): Promise<IsOperatorResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_operator: {
        address
      }
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  balance = async ({
    address
  }: {
    address: AndrAddr;
  }): Promise<BalanceResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance: {
        address
      }
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  module = async ({
    id
  }: {
    id: Uint64;
  }): Promise<Module> => {
    return this.client.queryContractSmart(this.contractAddress, {
      module: {
        id
      }
    });
  };
  moduleIds = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      module_ids: {}
    });
  };
}
export interface Cw20StakingContractTsInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addRewardToken: ({
    rewardToken
  }: {
    rewardToken: RewardTokenUnchecked;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unstakeTokens: ({
    amount
  }: {
    amount?: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateGlobalIndexes: ({
    assetInfos
  }: {
    assetInfos?: AssetInfoBaseForString[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerModule: ({
    module
  }: {
    module: Module;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deregisterModule: ({
    moduleIdx
  }: {
    moduleIdx: Uint64;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  alterModule: ({
    module,
    moduleIdx
  }: {
    module: Module;
    moduleIdx: Uint64;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class Cw20StakingContractTsClient implements Cw20StakingContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.addRewardToken = this.addRewardToken.bind(this);
    this.unstakeTokens = this.unstakeTokens.bind(this);
    this.claimRewards = this.claimRewards.bind(this);
    this.updateGlobalIndexes = this.updateGlobalIndexes.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.permissioning = this.permissioning.bind(this);
    this.registerModule = this.registerModule.bind(this);
    this.deregisterModule = this.deregisterModule.bind(this);
    this.alterModule = this.alterModule.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  addRewardToken = async ({
    rewardToken
  }: {
    rewardToken: RewardTokenUnchecked;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_reward_token: {
        reward_token: rewardToken
      }
    }, fee, memo, _funds);
  };
  unstakeTokens = async ({
    amount
  }: {
    amount?: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unstake_tokens: {
        amount
      }
    }, fee, memo, _funds);
  };
  claimRewards = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_rewards: {}
    }, fee, memo, _funds);
  };
  updateGlobalIndexes = async ({
    assetInfos
  }: {
    assetInfos?: AssetInfoBaseForString[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_global_indexes: {
        asset_infos: assetInfos
      }
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  permissioning = async (permissioningMessage: PermissioningMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permissioning: permissioningMessage
    }, fee, memo, _funds);
  };
  registerModule = async ({
    module
  }: {
    module: Module;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_module: {
        module
      }
    }, fee, memo, _funds);
  };
  deregisterModule = async ({
    moduleIdx
  }: {
    moduleIdx: Uint64;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deregister_module: {
        module_idx: moduleIdx
      }
    }, fee, memo, _funds);
  };
  alterModule = async ({
    module,
    moduleIdx
  }: {
    module: Module;
    moduleIdx: Uint64;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      alter_module: {
        module,
        module_idx: moduleIdx
      }
    }, fee, memo, _funds);
  };
}