/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, QueryMsg } from "./EconomicsContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class EconomicsContractTsExecuteMsgBuilder {
    static deposit: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        deposit: unknown;
    }>["deposit"]>) => ExecuteMsg;
    static payFee: ({ action, payee }: CamelCasedProperties<Extract<ExecuteMsg, {
        pay_fee: unknown;
    }>["pay_fee"]>) => ExecuteMsg;
    static withdraw: ({ amount, asset }: CamelCasedProperties<Extract<ExecuteMsg, {
        withdraw: unknown;
    }>["withdraw"]>) => ExecuteMsg;
    static withdrawCw20: ({ amount, asset }: CamelCasedProperties<Extract<ExecuteMsg, {
        withdraw_cw20: unknown;
    }>["withdraw_cw20"]>) => ExecuteMsg;
    static receive: ({ amount, msg, sender }: CamelCasedProperties<Extract<ExecuteMsg, {
        receive: unknown;
    }>["receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
}
export declare abstract class EconomicsContractTsQueryMsgBuilder {
    static balance: ({ address, asset }: CamelCasedProperties<Extract<QueryMsg, {
        balance: unknown;
    }>["balance"]>) => QueryMsg;
    static version: () => QueryMsg;
    static type: () => QueryMsg;
    static owner: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
}
