/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, InstantiateMsg, ExecuteMsg, Uint128, AndrAddr, ReplyOn, Binary, OwnershipMessage, Expiry, Milliseconds, PermissioningMessage, Permission, LocalPermission, RatesMessage, Rate, LocalRateType, LocalRateValue, Decimal, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, LocalRate, Recipient, PercentRate, QueryMsg, ADOBaseVersionResponse, AllRatesResponse, AppContractResponse, BlockHeightResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, NullableRate, NullableFullDelegation, FullDelegation, TypeResponse, NullableArrayOfUnstakingTokens, Timestamp, Uint64, UnstakingTokens, VersionResponse } from "./ValidatorStakingContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class ValidatorStakingContractTsExecuteMsgBuilder {
  static stake = ({
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    stake: unknown;
  }>["stake"]>): ExecuteMsg => {
    return {
      stake: ({
        validator
      } as const)
    };
  };
  static unstake = ({
    amount,
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    unstake: unknown;
  }>["unstake"]>): ExecuteMsg => {
    return {
      unstake: ({
        amount,
        validator
      } as const)
    };
  };
  static claim = ({
    recipient,
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    claim: unknown;
  }>["claim"]>): ExecuteMsg => {
    return {
      claim: ({
        recipient,
        validator
      } as const)
    };
  };
  static withdrawFunds = (): ExecuteMsg => {
    return {
      withdraw_funds: ({} as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static rates = (ratesMessage: RatesMessage): ExecuteMsg => {
    return {
      rates: ratesMessage
    };
  };
}
export abstract class ValidatorStakingContractTsQueryMsgBuilder {
  static stakedTokens = ({
    validator
  }: CamelCasedProperties<Extract<QueryMsg, {
    staked_tokens: unknown;
  }>["staked_tokens"]>): QueryMsg => {
    return {
      staked_tokens: ({
        validator
      } as const)
    };
  };
  static unstakedTokens = (): QueryMsg => {
    return {
      unstaked_tokens: ({} as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static rates = ({
    action
  }: CamelCasedProperties<Extract<QueryMsg, {
    rates: unknown;
  }>["rates"]>): QueryMsg => {
    return {
      rates: ({
        action
      } as const)
    };
  };
  static allRates = (): QueryMsg => {
    return {
      all_rates: ({} as const)
    };
  };
}