"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.Cw721ContractTsClient = exports.Cw721ContractTsQueryClient = void 0;
class Cw721ContractTsQueryClient {
    constructor(client, contractAddress) {
        this.ownerOf = async ({ includeExpired, tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                owner_of: {
                    include_expired: includeExpired,
                    token_id: tokenId
                }
            });
        };
        this.allOperators = async ({ includeExpired, limit, owner, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                all_operators: {
                    include_expired: includeExpired,
                    limit,
                    owner,
                    start_after: startAfter
                }
            });
        };
        this.numTokens = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                num_tokens: {}
            });
        };
        this.nftInfo = async ({ tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                nft_info: {
                    token_id: tokenId
                }
            });
        };
        this.allNftInfo = async ({ includeExpired, tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                all_nft_info: {
                    include_expired: includeExpired,
                    token_id: tokenId
                }
            });
        };
        this.tokens = async ({ limit, owner, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                tokens: {
                    limit,
                    owner,
                    start_after: startAfter
                }
            });
        };
        this.allTokens = async ({ limit, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                all_tokens: {
                    limit,
                    start_after: startAfter
                }
            });
        };
        this.isArchived = async ({ tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                is_archived: {
                    token_id: tokenId
                }
            });
        };
        this.transferAgreement = async ({ tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                transfer_agreement: {
                    token_id: tokenId
                }
            });
        };
        this.contractInfo = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                contract_info: {}
            });
        };
        this.minter = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                minter: {}
            });
        };
        this.approval = async ({ includeExpired, spender, tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                approval: {
                    include_expired: includeExpired,
                    spender,
                    token_id: tokenId
                }
            });
        };
        this.approvals = async ({ includeExpired, tokenId }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                approvals: {
                    include_expired: includeExpired,
                    token_id: tokenId
                }
            });
        };
        this.owner = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                owner: {}
            });
        };
        this.ownershipRequest = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                ownership_request: {}
            });
        };
        this.type = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                type: {}
            });
        };
        this.kernelAddress = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                kernel_address: {}
            });
        };
        this.appContract = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                app_contract: {}
            });
        };
        this.originalPublisher = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                original_publisher: {}
            });
        };
        this.blockHeightUponCreation = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                block_height_upon_creation: {}
            });
        };
        this.version = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                version: {}
            });
        };
        this.permissions = async ({ actor, limit, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissions: {
                    actor,
                    limit,
                    start_after: startAfter
                }
            });
        };
        this.permissionedActions = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissioned_actions: {}
            });
        };
        this.module = async ({ id }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                module: {
                    id
                }
            });
        };
        this.moduleIds = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                module_ids: {}
            });
        };
        this.client = client;
        this.contractAddress = contractAddress;
        this.ownerOf = this.ownerOf.bind(this);
        this.allOperators = this.allOperators.bind(this);
        this.numTokens = this.numTokens.bind(this);
        this.nftInfo = this.nftInfo.bind(this);
        this.allNftInfo = this.allNftInfo.bind(this);
        this.tokens = this.tokens.bind(this);
        this.allTokens = this.allTokens.bind(this);
        this.isArchived = this.isArchived.bind(this);
        this.transferAgreement = this.transferAgreement.bind(this);
        this.contractInfo = this.contractInfo.bind(this);
        this.minter = this.minter.bind(this);
        this.approval = this.approval.bind(this);
        this.approvals = this.approvals.bind(this);
        this.owner = this.owner.bind(this);
        this.ownershipRequest = this.ownershipRequest.bind(this);
        this.type = this.type.bind(this);
        this.kernelAddress = this.kernelAddress.bind(this);
        this.appContract = this.appContract.bind(this);
        this.originalPublisher = this.originalPublisher.bind(this);
        this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
        this.version = this.version.bind(this);
        this.permissions = this.permissions.bind(this);
        this.permissionedActions = this.permissionedActions.bind(this);
        this.module = this.module.bind(this);
        this.moduleIds = this.moduleIds.bind(this);
    }
}
exports.Cw721ContractTsQueryClient = Cw721ContractTsQueryClient;
class Cw721ContractTsClient {
    constructor(client, sender, contractAddress) {
        this.mint = async ({ extension, owner, tokenId, tokenUri }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                mint: {
                    extension,
                    owner,
                    token_id: tokenId,
                    token_uri: tokenUri
                }
            }, fee, memo, _funds);
        };
        this.transferNft = async ({ recipient, tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                transfer_nft: {
                    recipient,
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.sendNft = async ({ contract, msg, tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                send_nft: {
                    contract,
                    msg,
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.approve = async ({ expires, spender, tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                approve: {
                    expires,
                    spender,
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.revoke = async ({ spender, tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                revoke: {
                    spender,
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.approveAll = async ({ expires, operator }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                approve_all: {
                    expires,
                    operator
                }
            }, fee, memo, _funds);
        };
        this.revokeAll = async ({ operator }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                revoke_all: {
                    operator
                }
            }, fee, memo, _funds);
        };
        this.burn = async ({ tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                burn: {
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.archive = async ({ tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                archive: {
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.transferAgreement = async ({ agreement, tokenId }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                transfer_agreement: {
                    agreement,
                    token_id: tokenId
                }
            }, fee, memo, _funds);
        };
        this.batchMint = async ({ tokens }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                batch_mint: {
                    tokens
                }
            }, fee, memo, _funds);
        };
        this.ampReceive = async ({ ctx, messages }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                amp_receive: {
                    ctx,
                    messages
                }
            }, fee, memo, _funds);
        };
        this.ownership = async (ownershipMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                ownership: ownershipMessage
            }, fee, memo, _funds);
        };
        this.updateKernelAddress = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_kernel_address: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.updateAppContract = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_app_contract: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.permissioning = async (permissioningMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                permissioning: permissioningMessage
            }, fee, memo, _funds);
        };
        this.registerModule = async ({ module }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                register_module: {
                    module
                }
            }, fee, memo, _funds);
        };
        this.deregisterModule = async ({ moduleIdx }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                deregister_module: {
                    module_idx: moduleIdx
                }
            }, fee, memo, _funds);
        };
        this.alterModule = async ({ module, moduleIdx }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                alter_module: {
                    module,
                    module_idx: moduleIdx
                }
            }, fee, memo, _funds);
        };
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.mint = this.mint.bind(this);
        this.transferNft = this.transferNft.bind(this);
        this.sendNft = this.sendNft.bind(this);
        this.approve = this.approve.bind(this);
        this.revoke = this.revoke.bind(this);
        this.approveAll = this.approveAll.bind(this);
        this.revokeAll = this.revokeAll.bind(this);
        this.burn = this.burn.bind(this);
        this.archive = this.archive.bind(this);
        this.transferAgreement = this.transferAgreement.bind(this);
        this.batchMint = this.batchMint.bind(this);
        this.ampReceive = this.ampReceive.bind(this);
        this.ownership = this.ownership.bind(this);
        this.updateKernelAddress = this.updateKernelAddress.bind(this);
        this.updateAppContract = this.updateAppContract.bind(this);
        this.permissioning = this.permissioning.bind(this);
        this.registerModule = this.registerModule.bind(this);
        this.deregisterModule = this.deregisterModule.bind(this);
        this.alterModule = this.alterModule.bind(this);
    }
}
exports.Cw721ContractTsClient = Cw721ContractTsClient;
