/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, MinimumFrequency, Milliseconds, InstantiateMsg, CoinAndLimit, ExecuteMsg, AndrAddr, ReplyOn, Binary, OwnershipMessage, Expiry, Addr, PermissioningMessage, Permission, LocalPermission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, ADOBaseVersionResponse, Timestamp, Uint64, AccountDetails, AppContractResponse, BlockHeightResponse, CoinAllowance, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./RateLimitingWithdrawalsContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class RateLimitingWithdrawalsContractTsExecuteMsgBuilder {
  static deposit = ({
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deposit: unknown;
  }>["deposit"]>): ExecuteMsg => {
    return {
      deposit: ({
        recipient
      } as const)
    };
  };
  static withdraw = ({
    amount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw: unknown;
  }>["withdraw"]>): ExecuteMsg => {
    return {
      withdraw: ({
        amount
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
}
export abstract class RateLimitingWithdrawalsContractTsQueryMsgBuilder {
  static coinAllowanceDetails = (): QueryMsg => {
    return {
      coin_allowance_details: ({} as const)
    };
  };
  static accountDetails = ({
    account
  }: CamelCasedProperties<Extract<QueryMsg, {
    account_details: unknown;
  }>["account_details"]>): QueryMsg => {
    return {
      account_details: ({
        account
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
}