/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AndrAddr = string;
export interface InstantiateMsg {
  authorized_token_addresses?: AndrAddr[] | null;
  kernel_address: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  receive_nft: Cw721ReceiveMsg;
} | {
  claim_nft: {
    cw721_contract: AndrAddr;
    token_id: string;
  };
} | {
  amp_receive: AMPPkt;
} | {
  ownership: OwnershipMessage;
} | {
  update_kernel_address: {
    address: Addr;
  };
} | {
  update_app_contract: {
    address: string;
  };
} | {
  permissioning: PermissioningMessage;
};
export type Binary = string;
export type ReplyOn = "always" | "error" | "success" | "never";
export type Uint128 = string;
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Milliseconds | null;
    new_owner: Addr;
  };
};
export type Milliseconds = number;
export type Addr = string;
export type PermissioningMessage = {
  set_permission: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  };
} | {
  remove_permission: {
    action: string;
    actor: AndrAddr;
  };
} | {
  permission_action: {
    action: string;
  };
} | {
  disable_action_permissioning: {
    action: string;
  };
};
export type Permission = {
  blacklisted: Milliseconds | null;
} | {
  limited: {
    expiration?: Milliseconds | null;
    uses: number;
  };
} | {
  whitelisted: Milliseconds | null;
};
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id: number;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_sender: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  unlock_time: {
    cw721_contract: AndrAddr;
    token_id: string;
  };
} | {
  nft_details: {
    cw721_contract: AndrAddr;
    token_id: string;
  };
} | {
  is_locked: {
    cw721_contract: AndrAddr;
    token_id: string;
  };
} | {
  owner: {};
} | {
  ownership_request: {};
} | {
  type: {};
} | {
  kernel_address: {};
} | {
  app_contract: {};
} | {
  original_publisher: {};
} | {
  block_height_upon_creation: {};
} | {
  version: {};
} | {
  permissions: {
    actor: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  permissioned_actions: {};
};
export interface AppContractResponse {
  app_contract: Addr;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface IsLockedResponse {
  is_locked: boolean;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export interface NftDetailsResponse {
  recipient: Addr;
  unlock_time: number;
}
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface ContractPotentialOwnerResponse {
  expiration?: Milliseconds | null;
  potential_owner?: Addr | null;
}
export type ArrayOfString = string[];
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export interface TypeResponse {
  ado_type: string;
}
export interface UnlockTimeResponse {
  unlock_time: number;
}
export interface VersionResponse {
  version: string;
}
export type Cw721TimelockContractTsExecuteMsg = ExecuteMsg;