/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AndrAddr = string;
export interface InstantiateMsg {
  deposit_window: number;
  incentive_token: string;
  init_timestamp: number;
  kernel_address: string;
  modules?: Module[] | null;
  native_denom: string;
  owner?: string | null;
  withdrawal_window: number;
}
export interface Module {
  address: AndrAddr;
  is_mutable: boolean;
  name?: string | null;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  deposit_native: {};
} | {
  withdraw_native: {
    amount?: Uint128 | null;
  };
} | {
  claim_rewards: {};
} | {
  enable_claims: {};
} | {
  amp_receive: AMPPkt;
} | {
  ownership: OwnershipMessage;
} | {
  update_kernel_address: {
    address: Addr;
  };
} | {
  update_app_contract: {
    address: string;
  };
} | {
  set_permission: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  };
} | {
  remove_permission: {
    action: string;
    actor: AndrAddr;
  };
} | {
  permission_action: {
    action: string;
  };
} | {
  register_module: {
    module: Module;
  };
} | {
  deregister_module: {
    module_idx: Uint64;
  };
} | {
  alter_module: {
    module: Module;
    module_idx: Uint64;
  };
};
export type Uint128 = string;
export type Binary = string;
export type ReplyOn = "always" | "error" | "success" | "never";
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Expiration | null;
    new_owner: Addr;
  };
} | {
  update_operators: {
    new_operators: Addr[];
  };
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Addr = string;
export type Permission = {
  blacklisted: Expiration | null;
} | {
  limited: {
    expiration?: Expiration | null;
    uses: number;
  };
} | {
  whitelisted: Expiration | null;
};
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id: number;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_sender: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {};
} | {
  state: {};
} | {
  user_info: {
    address: string;
  };
} | {
  withdrawal_percent_allowed: {
    timestamp?: number | null;
  };
} | {
  owner: {};
} | {
  operators: {};
} | {
  type: {};
} | {
  kernel_address: {};
} | {
  original_publisher: {};
} | {
  block_height_upon_creation: {};
} | {
  is_operator: {
    address: string;
  };
} | {
  version: {};
} | {
  balance: {
    address: AndrAddr;
  };
} | {
  permissions: {
    actor: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  permissioned_actions: {};
} | {
  module: {
    id: Uint64;
  };
} | {
  module_ids: {};
};
export interface BalanceResponse {
  amount: Coin;
  [k: string]: unknown;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface ConfigResponse {
  deposit_window: number;
  incentive_token: string;
  init_timestamp: number;
  lockdrop_incentives: Uint128;
  native_denom: string;
  withdrawal_window: number;
}
export interface IsOperatorResponse {
  is_operator: boolean;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export type ArrayOfString = string[];
export interface OperatorsResponse {
  operators: string[];
}
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export interface StateResponse {
  are_claims_allowed: boolean;
  total_native_locked: Uint128;
}
export interface TypeResponse {
  ado_type: string;
}
export interface UserInfoResponse {
  is_lockdrop_claimed: boolean;
  total_incentives: Uint128;
  total_native_locked: Uint128;
  withdrawal_flag: boolean;
}
export interface VersionResponse {
  version: string;
}
export type Decimal = string;
export type LockdropContractTsExecuteMsg = ExecuteMsg;