/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg, AndromedaHook } from "./PrimitiveContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class PrimitiveContractTsExecuteMsgBuilder {
    static setValue: ({ key, value }: CamelCasedProperties<Extract<ExecuteMsg, {
        set_value: unknown;
    }>["set_value"]>) => ExecuteMsg;
    static deleteValue: ({ key }: CamelCasedProperties<Extract<ExecuteMsg, {
        delete_value: unknown;
    }>["delete_value"]>) => ExecuteMsg;
    static updateRestriction: ({ restriction }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_restriction: unknown;
    }>["update_restriction"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
}
export declare abstract class PrimitiveContractTsQueryMsgBuilder {
    static getValue: ({ key }: CamelCasedProperties<Extract<QueryMsg, {
        get_value: unknown;
    }>["get_value"]>) => QueryMsg;
    static allKeys: () => QueryMsg;
    static ownerKeys: ({ owner }: CamelCasedProperties<Extract<QueryMsg, {
        owner_keys: unknown;
    }>["owner_keys"]>) => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
    static andrHook: (andromedaHook: AndromedaHook) => QueryMsg;
}
