/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, InstantiateMsg, Module, ExecuteMsg, Milliseconds, Uint128, Binary, ReplyOn, OwnershipMessage, Addr, PermissioningMessage, Permission, Uint64, CrowdfundMintMsg, TokenExtension, Coin, Recipient, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, QueryMsg, AppContractResponse, ArrayOfString, BlockHeightResponse, Config, Boolean, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, Expiration, Timestamp, State, TypeResponse, VersionResponse } from "./CrowdfundContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class CrowdfundContractTsExecuteMsgBuilder {
  static mint = (msgs: CrowdfundMintMsg[]): ExecuteMsg => {
    return {
      mint: msgs
    };
  };
  static startSale = ({
    endTime,
    maxAmountPerWallet,
    minTokensSold,
    price,
    recipient,
    startTime
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    start_sale: unknown;
  }>["start_sale"]>): ExecuteMsg => {
    return {
      start_sale: ({
        end_time: endTime,
        max_amount_per_wallet: maxAmountPerWallet,
        min_tokens_sold: minTokensSold,
        price,
        recipient,
        start_time: startTime
      } as const)
    };
  };
  static updateTokenContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_token_contract: unknown;
  }>["update_token_contract"]>): ExecuteMsg => {
    return {
      update_token_contract: ({
        address
      } as const)
    };
  };
  static purchase = ({
    numberOfTokens
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    purchase: unknown;
  }>["purchase"]>): ExecuteMsg => {
    return {
      purchase: ({
        number_of_tokens: numberOfTokens
      } as const)
    };
  };
  static purchaseByTokenId = ({
    tokenId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    purchase_by_token_id: unknown;
  }>["purchase_by_token_id"]>): ExecuteMsg => {
    return {
      purchase_by_token_id: ({
        token_id: tokenId
      } as const)
    };
  };
  static claimRefund = (): ExecuteMsg => {
    return {
      claim_refund: ({} as const)
    };
  };
  static endSale = ({
    limit
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    end_sale: unknown;
  }>["end_sale"]>): ExecuteMsg => {
    return {
      end_sale: ({
        limit
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static registerModule = ({
    module
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_module: unknown;
  }>["register_module"]>): ExecuteMsg => {
    return {
      register_module: ({
        module
      } as const)
    };
  };
  static deregisterModule = ({
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deregister_module: unknown;
  }>["deregister_module"]>): ExecuteMsg => {
    return {
      deregister_module: ({
        module_idx: moduleIdx
      } as const)
    };
  };
  static alterModule = ({
    module,
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    alter_module: unknown;
  }>["alter_module"]>): ExecuteMsg => {
    return {
      alter_module: ({
        module,
        module_idx: moduleIdx
      } as const)
    };
  };
}
export abstract class CrowdfundContractTsQueryMsgBuilder {
  static state = (): QueryMsg => {
    return {
      state: ({} as const)
    };
  };
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static availableTokens = ({
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    available_tokens: unknown;
  }>["available_tokens"]>): QueryMsg => {
    return {
      available_tokens: ({
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static isTokenAvailable = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    is_token_available: unknown;
  }>["is_token_available"]>): QueryMsg => {
    return {
      is_token_available: ({
        id
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static module = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    module: unknown;
  }>["module"]>): QueryMsg => {
    return {
      module: ({
        id
      } as const)
    };
  };
  static moduleIds = (): QueryMsg => {
    return {
      module_ids: ({} as const)
    };
  };
}