/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AndrAddr, Binary, Uint128, InstantiateMsg, AddressWeight, Recipient, ExecuteMsg, ReplyOn, OwnershipMessage, Expiry, Milliseconds, Addr, PermissioningMessage, Permission, LocalPermission, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, ADOBaseVersionResponse, AppContractResponse, BlockHeightResponse, Expiration, Timestamp, Uint64, GetSplitterConfigResponse, Splitter, GetUserWeightResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./WeightedDistributionSplitterContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class WeightedDistributionSplitterContractTsExecuteMsgBuilder {
  static updateRecipients = ({
    recipients
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_recipients: unknown;
  }>["update_recipients"]>): ExecuteMsg => {
    return {
      update_recipients: ({
        recipients
      } as const)
    };
  };
  static updateRecipientWeight = ({
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_recipient_weight: unknown;
  }>["update_recipient_weight"]>): ExecuteMsg => {
    return {
      update_recipient_weight: ({
        recipient
      } as const)
    };
  };
  static addRecipient = ({
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    add_recipient: unknown;
  }>["add_recipient"]>): ExecuteMsg => {
    return {
      add_recipient: ({
        recipient
      } as const)
    };
  };
  static removeRecipient = ({
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    remove_recipient: unknown;
  }>["remove_recipient"]>): ExecuteMsg => {
    return {
      remove_recipient: ({
        recipient
      } as const)
    };
  };
  static updateLock = ({
    lockTime
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_lock: unknown;
  }>["update_lock"]>): ExecuteMsg => {
    return {
      update_lock: ({
        lock_time: lockTime
      } as const)
    };
  };
  static send = (): ExecuteMsg => {
    return {
      send: ({} as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
}
export abstract class WeightedDistributionSplitterContractTsQueryMsgBuilder {
  static getSplitterConfig = (): QueryMsg => {
    return {
      get_splitter_config: ({} as const)
    };
  };
  static getUserWeight = ({
    user
  }: CamelCasedProperties<Extract<QueryMsg, {
    get_user_weight: unknown;
  }>["get_user_weight"]>): QueryMsg => {
    return {
      get_user_weight: ({
        user
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static aDOBaseVersion = (): QueryMsg => {
    return {
      a_d_o_base_version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
}