"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddressListContractTsClient = exports.AddressListContractTsQueryClient = void 0;
class AddressListContractTsQueryClient {
    constructor(client, contractAddress) {
        this.includesAddress = async ({ address }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                includes_address: {
                    address
                }
            });
        };
        this.isInclusive = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                is_inclusive: {}
            });
        };
        this.owner = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                owner: {}
            });
        };
        this.ownershipRequest = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                ownership_request: {}
            });
        };
        this.type = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                type: {}
            });
        };
        this.kernelAddress = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                kernel_address: {}
            });
        };
        this.appContract = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                app_contract: {}
            });
        };
        this.originalPublisher = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                original_publisher: {}
            });
        };
        this.blockHeightUponCreation = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                block_height_upon_creation: {}
            });
        };
        this.version = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                version: {}
            });
        };
        this.permissions = async ({ actor, limit, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissions: {
                    actor,
                    limit,
                    start_after: startAfter
                }
            });
        };
        this.permissionedActions = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissioned_actions: {}
            });
        };
        this.andrHook = async (andromedaHook) => {
            return this.client.queryContractSmart(this.contractAddress, {
                andr_hook: andromedaHook
            });
        };
        this.client = client;
        this.contractAddress = contractAddress;
        this.includesAddress = this.includesAddress.bind(this);
        this.isInclusive = this.isInclusive.bind(this);
        this.owner = this.owner.bind(this);
        this.ownershipRequest = this.ownershipRequest.bind(this);
        this.type = this.type.bind(this);
        this.kernelAddress = this.kernelAddress.bind(this);
        this.appContract = this.appContract.bind(this);
        this.originalPublisher = this.originalPublisher.bind(this);
        this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
        this.version = this.version.bind(this);
        this.permissions = this.permissions.bind(this);
        this.permissionedActions = this.permissionedActions.bind(this);
        this.andrHook = this.andrHook.bind(this);
    }
}
exports.AddressListContractTsQueryClient = AddressListContractTsQueryClient;
class AddressListContractTsClient {
    constructor(client, sender, contractAddress) {
        this.addAddress = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                add_address: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.removeAddress = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                remove_address: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.addAddresses = async ({ addresses }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                add_addresses: {
                    addresses
                }
            }, fee, memo, _funds);
        };
        this.ampReceive = async ({ ctx, messages }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                amp_receive: {
                    ctx,
                    messages
                }
            }, fee, memo, _funds);
        };
        this.ownership = async (ownershipMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                ownership: ownershipMessage
            }, fee, memo, _funds);
        };
        this.updateKernelAddress = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_kernel_address: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.updateAppContract = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_app_contract: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.permissioning = async (permissioningMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                permissioning: permissioningMessage
            }, fee, memo, _funds);
        };
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.addAddress = this.addAddress.bind(this);
        this.removeAddress = this.removeAddress.bind(this);
        this.addAddresses = this.addAddresses.bind(this);
        this.ampReceive = this.ampReceive.bind(this);
        this.ownership = this.ownership.bind(this);
        this.updateKernelAddress = this.updateKernelAddress.bind(this);
        this.updateAppContract = this.updateAppContract.bind(this);
        this.permissioning = this.permissioning.bind(this);
    }
}
exports.AddressListContractTsClient = AddressListContractTsClient;
