/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg, AndromedaHook } from "./AddressListContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class AddressListContractTsExecuteMsgBuilder {
    static addAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_address: unknown;
    }>["add_address"]>) => ExecuteMsg;
    static removeAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        remove_address: unknown;
    }>["remove_address"]>) => ExecuteMsg;
    static addAddresses: ({ addresses }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_addresses: unknown;
    }>["add_addresses"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
}
export declare abstract class AddressListContractTsQueryMsgBuilder {
    static includesAddress: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        includes_address: unknown;
    }>["includes_address"]>) => QueryMsg;
    static isInclusive: () => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
    static andrHook: (andromedaHook: AndromedaHook) => QueryMsg;
}
