/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, Addr, ActionFee, QueryMsg, NullableADOMetadata, ADOMetadata, NullableString, ArrayOfString, NullableActionFee, Uint64 } from "./AdodbContractTs.types";
export interface AdodbContractTsReadOnlyInterface {
  contractAddress: string;
  codeId: ({
    key
  }: {
    key: string;
  }) => Promise<Uint64>;
  adoType: ({
    codeId
  }: {
    codeId: number;
  }) => Promise<string>;
  allAdoTypes: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<Array<string>>;
  adoVersions: ({
    adoType,
    limit,
    startAfter
  }: {
    adoType: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<any>;
  adoMetadata: ({
    adoType
  }: {
    adoType: string;
  }) => Promise<ADOMetadata>;
  actionFee: ({
    action,
    adoType
  }: {
    action: string;
    adoType: string;
  }) => Promise<NullableActionFee>;
  actionFeeByCodeId: ({
    action,
    codeId
  }: {
    action: string;
    codeId: number;
  }) => Promise<NullableActionFee>;
}
export class AdodbContractTsQueryClient implements AdodbContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.codeId = this.codeId.bind(this);
    this.adoType = this.adoType.bind(this);
    this.allAdoTypes = this.allAdoTypes.bind(this);
    this.adoVersions = this.adoVersions.bind(this);
    this.adoMetadata = this.adoMetadata.bind(this);
    this.actionFee = this.actionFee.bind(this);
    this.actionFeeByCodeId = this.actionFeeByCodeId.bind(this);
  }

  codeId = async ({
    key
  }: {
    key: string;
  }): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      code_id: {
        key
      }
    });
  };
  adoType = async ({
    codeId
  }: {
    codeId: number;
  }): Promise<string> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ado_type: {
        code_id: codeId
      }
    });
  };
  allAdoTypes = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<Array<string>> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_ado_types: {
        limit,
        start_after: startAfter
      }
    });
  };
  adoVersions = async ({
    adoType,
    limit,
    startAfter
  }: {
    adoType: string;
    limit?: number;
    startAfter?: string;
  }): Promise<any> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ado_versions: {
        ado_type: adoType,
        limit,
        start_after: startAfter
      }
    });
  };
  adoMetadata = async ({
    adoType
  }: {
    adoType: string;
  }): Promise<ADOMetadata> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ado_metadata: {
        ado_type: adoType
      }
    });
  };
  actionFee = async ({
    action,
    adoType
  }: {
    action: string;
    adoType: string;
  }): Promise<NullableActionFee> => {
    return this.client.queryContractSmart(this.contractAddress, {
      action_fee: {
        action,
        ado_type: adoType
      }
    });
  };
  actionFeeByCodeId = async ({
    action,
    codeId
  }: {
    action: string;
    codeId: number;
  }): Promise<NullableActionFee> => {
    return this.client.queryContractSmart(this.contractAddress, {
      action_fee_by_code_id: {
        action,
        code_id: codeId
      }
    });
  };
}
export interface AdodbContractTsInterface {
  contractAddress: string;
  sender: string;
  publish: ({
    actionFees,
    adoType,
    codeId,
    publisher,
    version
  }: {
    actionFees?: ActionFee[];
    adoType: string;
    codeId: number;
    publisher?: string;
    version: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateActionFees: ({
    actionFees,
    adoType
  }: {
    actionFees: ActionFee[];
    adoType: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeActionFees: ({
    actions,
    adoType
  }: {
    actions: string[];
    adoType: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updatePublisher: ({
    adoType,
    publisher
  }: {
    adoType: string;
    publisher: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class AdodbContractTsClient implements AdodbContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.publish = this.publish.bind(this);
    this.updateActionFees = this.updateActionFees.bind(this);
    this.removeActionFees = this.removeActionFees.bind(this);
    this.updatePublisher = this.updatePublisher.bind(this);
  }

  publish = async ({
    actionFees,
    adoType,
    codeId,
    publisher,
    version
  }: {
    actionFees?: ActionFee[];
    adoType: string;
    codeId: number;
    publisher?: string;
    version: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      publish: {
        action_fees: actionFees,
        ado_type: adoType,
        code_id: codeId,
        publisher,
        version
      }
    }, fee, memo, _funds);
  };
  updateActionFees = async ({
    actionFees,
    adoType
  }: {
    actionFees: ActionFee[];
    adoType: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_action_fees: {
        action_fees: actionFees,
        ado_type: adoType
      }
    }, fee, memo, _funds);
  };
  removeActionFees = async ({
    actions,
    adoType
  }: {
    actions: string[];
    adoType: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_action_fees: {
        actions,
        ado_type: adoType
      }
    }, fee, memo, _funds);
  };
  updatePublisher = async ({
    adoType,
    publisher
  }: {
    adoType: string;
    publisher: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_publisher: {
        ado_type: adoType,
        publisher
      }
    }, fee, memo, _funds);
  };
}