/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, Uint128, Addr, ActionFee, QueryMsg, NullableADOMetadata, ADOMetadata, NullableString, ArrayOfString, NullableActionFee, Uint64 } from "./AdodbContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class AdodbContractTsExecuteMsgBuilder {
  static publish = ({
    actionFees,
    adoType,
    codeId,
    publisher,
    version
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    publish: unknown;
  }>["publish"]>): ExecuteMsg => {
    return {
      publish: ({
        action_fees: actionFees,
        ado_type: adoType,
        code_id: codeId,
        publisher,
        version
      } as const)
    };
  };
  static updateActionFees = ({
    actionFees,
    adoType
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_action_fees: unknown;
  }>["update_action_fees"]>): ExecuteMsg => {
    return {
      update_action_fees: ({
        action_fees: actionFees,
        ado_type: adoType
      } as const)
    };
  };
  static removeActionFees = ({
    actions,
    adoType
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    remove_action_fees: unknown;
  }>["remove_action_fees"]>): ExecuteMsg => {
    return {
      remove_action_fees: ({
        actions,
        ado_type: adoType
      } as const)
    };
  };
  static updatePublisher = ({
    adoType,
    publisher
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_publisher: unknown;
  }>["update_publisher"]>): ExecuteMsg => {
    return {
      update_publisher: ({
        ado_type: adoType,
        publisher
      } as const)
    };
  };
}
export abstract class AdodbContractTsQueryMsgBuilder {
  static codeId = ({
    key
  }: CamelCasedProperties<Extract<QueryMsg, {
    code_id: unknown;
  }>["code_id"]>): QueryMsg => {
    return {
      code_id: ({
        key
      } as const)
    };
  };
  static adoType = ({
    codeId
  }: CamelCasedProperties<Extract<QueryMsg, {
    ado_type: unknown;
  }>["ado_type"]>): QueryMsg => {
    return {
      ado_type: ({
        code_id: codeId
      } as const)
    };
  };
  static allAdoTypes = ({
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    all_ado_types: unknown;
  }>["all_ado_types"]>): QueryMsg => {
    return {
      all_ado_types: ({
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static adoVersions = ({
    adoType,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    ado_versions: unknown;
  }>["ado_versions"]>): QueryMsg => {
    return {
      ado_versions: ({
        ado_type: adoType,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static adoMetadata = ({
    adoType
  }: CamelCasedProperties<Extract<QueryMsg, {
    ado_metadata: unknown;
  }>["ado_metadata"]>): QueryMsg => {
    return {
      ado_metadata: ({
        ado_type: adoType
      } as const)
    };
  };
  static actionFee = ({
    action,
    adoType
  }: CamelCasedProperties<Extract<QueryMsg, {
    action_fee: unknown;
  }>["action_fee"]>): QueryMsg => {
    return {
      action_fee: ({
        action,
        ado_type: adoType
      } as const)
    };
  };
  static actionFeeByCodeId = ({
    action,
    codeId
  }: CamelCasedProperties<Extract<QueryMsg, {
    action_fee_by_code_id: unknown;
  }>["action_fee_by_code_id"]>): QueryMsg => {
    return {
      action_fee_by_code_id: ({
        action,
        code_id: codeId
      } as const)
    };
  };
}