/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  kernel_address: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  withdraw_vault: {
    recipient?: Recipient | null;
    strategy?: StrategyType | null;
    withdrawals: Withdrawal[];
  };
} | {
  update_strategy: {
    address: AndrAddr;
    strategy: StrategyType;
  };
} | {
  withdraw: {
    recipient?: Recipient | null;
    tokens_to_withdraw?: Withdrawal[] | null;
  };
} | {
  deposit: {
    msg?: Binary | null;
    recipient?: AndrAddr | null;
  };
} | {
  amp_receive: AMPPkt;
} | {
  ownership: OwnershipMessage;
} | {
  update_kernel_address: {
    address: Addr;
  };
} | {
  update_app_contract: {
    address: string;
  };
} | {
  permissioning: PermissioningMessage;
};
export type AndrAddr = string;
export type Binary = string;
export type StrategyType = "anchor";
export type WithdrawalType = {
  amount: Uint128;
} | {
  percentage: Decimal;
};
export type Uint128 = string;
export type Decimal = string;
export type ReplyOn = "always" | "error" | "success" | "never";
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Expiry | null;
    new_owner: Addr;
  };
};
export type Expiry = {
  from_now: Milliseconds;
} | {
  at_time: Milliseconds;
};
export type Milliseconds = number;
export type Addr = string;
export type PermissioningMessage = {
  set_permission: {
    action: string;
    actors: AndrAddr[];
    permission: Permission;
  };
} | {
  remove_permission: {
    action: string;
    actors: AndrAddr[];
  };
} | {
  permission_action: {
    action: string;
  };
} | {
  disable_action_permissioning: {
    action: string;
  };
};
export type Permission = {
  local: LocalPermission;
} | {
  contract: AndrAddr;
};
export type LocalPermission = {
  blacklisted: Expiry | null;
} | {
  limited: {
    expiration?: Expiry | null;
    uses: number;
  };
} | {
  whitelisted: Expiry | null;
};
export interface Recipient {
  address: AndrAddr;
  ibc_recovery_address?: AndrAddr | null;
  msg?: Binary | null;
}
export interface Withdrawal {
  token: string;
  withdrawal_type?: WithdrawalType | null;
}
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id: number;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_sender: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  vault_balance: {
    address: AndrAddr;
    denom?: string | null;
    strategy?: StrategyType | null;
  };
} | {
  strategy_address: {
    strategy: StrategyType;
  };
} | {
  owner: {};
} | {
  ownership_request: {};
} | {
  type: {};
} | {
  kernel_address: {};
} | {
  app_contract: {};
} | {
  original_publisher: {};
} | {
  block_height_upon_creation: {};
} | {
  version: {};
} | {
  a_d_o_base_version: {};
} | {
  permissions: {
    actor: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  permissioned_actions: {};
};
export interface ADOBaseVersionResponse {
  version: string;
}
export interface AppContractResponse {
  app_contract: Addr;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface ContractPotentialOwnerResponse {
  expiration?: Milliseconds | null;
  potential_owner?: Addr | null;
}
export type ArrayOfString = string[];
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export interface StrategyAddressResponse {
  address: string;
  strategy: StrategyType;
}
export interface TypeResponse {
  ado_type: string;
}
export interface VersionResponse {
  version: string;
}
export type VaultContractTsExecuteMsg = ExecuteMsg;