/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AndrAddr = string;
export interface InstantiateMsg {
  authorized_cw20_address?: AndrAddr | null;
  kernel_address: string;
  owner?: string | null;
}
export type ExecuteMsg = {
  receive_nft: Cw721ReceiveMsg;
} | {
  receive: Cw20ReceiveMsg;
} | {
  buy: {
    token_address: string;
    token_id: string;
  };
} | {
  update_sale: {
    coin_denom: Asset;
    price: Uint128;
    recipient?: Recipient | null;
    token_address: string;
    token_id: string;
  };
} | {
  cancel_sale: {
    token_address: string;
    token_id: string;
  };
} | {
  amp_receive: AMPPkt;
} | {
  ownership: OwnershipMessage;
} | {
  update_kernel_address: {
    address: Addr;
  };
} | {
  update_app_contract: {
    address: string;
  };
} | {
  permissioning: PermissioningMessage;
} | {
  rates: RatesMessage;
};
export type Binary = string;
export type Uint128 = string;
export type Asset = {
  cw20_token: AndrAddr;
} | {
  native_token: string;
};
export type ReplyOn = "always" | "error" | "success" | "never";
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Expiry | null;
    new_owner: Addr;
  };
};
export type Expiry = {
  from_now: Milliseconds;
} | {
  at_time: Milliseconds;
};
export type Milliseconds = number;
export type Addr = string;
export type PermissioningMessage = {
  set_permission: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  };
} | {
  remove_permission: {
    action: string;
    actor: AndrAddr;
  };
} | {
  permission_action: {
    action: string;
  };
} | {
  disable_action_permissioning: {
    action: string;
  };
};
export type Permission = {
  local: LocalPermission;
} | {
  contract: AndrAddr;
};
export type LocalPermission = {
  blacklisted: Expiry | null;
} | {
  limited: {
    expiration?: Expiry | null;
    uses: number;
  };
} | {
  whitelisted: Expiry | null;
};
export type RatesMessage = {
  set_rate: {
    action: string;
    rate: Rate;
  };
} | {
  remove_rate: {
    action: string;
  };
};
export type Rate = {
  local: LocalRate;
} | {
  contract: AndrAddr;
};
export type LocalRateType = "additive" | "deductive";
export type LocalRateValue = {
  percent: PercentRate;
} | {
  flat: Coin;
};
export type Decimal = string;
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface Recipient {
  address: AndrAddr;
  ibc_recovery_address?: AndrAddr | null;
  msg?: Binary | null;
}
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id: number;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_sender: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface LocalRate {
  description?: string | null;
  rate_type: LocalRateType;
  recipients: Recipient[];
  value: LocalRateValue;
}
export interface PercentRate {
  percent: Decimal;
}
export type QueryMsg = {
  latest_sale_state: {
    token_address: string;
    token_id: string;
  };
} | {
  sale_state: {
    sale_id: Uint128;
  };
} | {
  sale_ids: {
    token_address: string;
    token_id: string;
  };
} | {
  sale_infos_for_address: {
    limit?: number | null;
    start_after?: string | null;
    token_address: string;
  };
} | {
  owner: {};
} | {
  ownership_request: {};
} | {
  type: {};
} | {
  kernel_address: {};
} | {
  app_contract: {};
} | {
  original_publisher: {};
} | {
  block_height_upon_creation: {};
} | {
  version: {};
} | {
  a_d_o_base_version: {};
} | {
  permissions: {
    actor: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  permissioned_actions: {};
} | {
  rates: {
    action: string;
  };
} | {
  all_rates: {};
};
export interface ADOBaseVersionResponse {
  version: string;
}
export interface AllRatesResponse {
  all_rates: [string, Rate][];
}
export interface AppContractResponse {
  app_contract: Addr;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Status = "open" | "expired" | "executed" | "cancelled";
export interface SaleStateResponse {
  coin_denom: string;
  end_time: Expiration;
  price: Uint128;
  recipient?: Recipient | null;
  sale_id: Uint128;
  start_time: Expiration;
  status: Status;
}
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface ContractPotentialOwnerResponse {
  expiration?: Milliseconds | null;
  potential_owner?: Addr | null;
}
export type ArrayOfString = string[];
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export type NullableRate = Rate | null;
export interface SaleIdsResponse {
  sale_ids: Uint128[];
}
export type ArrayOfSaleInfo = SaleInfo[];
export interface SaleInfo {
  sale_ids: Uint128[];
  token_address: string;
  token_id: string;
}
export interface TypeResponse {
  ado_type: string;
}
export interface VersionResponse {
  version: string;
}
export type MarketplaceContractTsExecuteMsg = ExecuteMsg;