"use strict";
/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.LockdropContractTsClient = exports.LockdropContractTsQueryClient = void 0;
class LockdropContractTsQueryClient {
    constructor(client, contractAddress) {
        this.config = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                config: {}
            });
        };
        this.state = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                state: {}
            });
        };
        this.userInfo = async ({ address }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                user_info: {
                    address
                }
            });
        };
        this.withdrawalPercentAllowed = async ({ timestamp }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                withdrawal_percent_allowed: {
                    timestamp
                }
            });
        };
        this.owner = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                owner: {}
            });
        };
        this.ownershipRequest = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                ownership_request: {}
            });
        };
        this.type = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                type: {}
            });
        };
        this.kernelAddress = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                kernel_address: {}
            });
        };
        this.appContract = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                app_contract: {}
            });
        };
        this.originalPublisher = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                original_publisher: {}
            });
        };
        this.blockHeightUponCreation = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                block_height_upon_creation: {}
            });
        };
        this.version = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                version: {}
            });
        };
        this.permissions = async ({ actor, limit, startAfter }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissions: {
                    actor,
                    limit,
                    start_after: startAfter
                }
            });
        };
        this.permissionedActions = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                permissioned_actions: {}
            });
        };
        this.module = async ({ id }) => {
            return this.client.queryContractSmart(this.contractAddress, {
                module: {
                    id
                }
            });
        };
        this.moduleIds = async () => {
            return this.client.queryContractSmart(this.contractAddress, {
                module_ids: {}
            });
        };
        this.andrHook = async (andromedaHook) => {
            return this.client.queryContractSmart(this.contractAddress, {
                andr_hook: andromedaHook
            });
        };
        this.client = client;
        this.contractAddress = contractAddress;
        this.config = this.config.bind(this);
        this.state = this.state.bind(this);
        this.userInfo = this.userInfo.bind(this);
        this.withdrawalPercentAllowed = this.withdrawalPercentAllowed.bind(this);
        this.owner = this.owner.bind(this);
        this.ownershipRequest = this.ownershipRequest.bind(this);
        this.type = this.type.bind(this);
        this.kernelAddress = this.kernelAddress.bind(this);
        this.appContract = this.appContract.bind(this);
        this.originalPublisher = this.originalPublisher.bind(this);
        this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
        this.version = this.version.bind(this);
        this.permissions = this.permissions.bind(this);
        this.permissionedActions = this.permissionedActions.bind(this);
        this.module = this.module.bind(this);
        this.moduleIds = this.moduleIds.bind(this);
        this.andrHook = this.andrHook.bind(this);
    }
}
exports.LockdropContractTsQueryClient = LockdropContractTsQueryClient;
class LockdropContractTsClient {
    constructor(client, sender, contractAddress) {
        this.receive = async ({ amount, msg, sender }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                receive: {
                    amount,
                    msg,
                    sender
                }
            }, fee, memo, _funds);
        };
        this.depositNative = async (fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                deposit_native: {}
            }, fee, memo, _funds);
        };
        this.withdrawNative = async ({ amount }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                withdraw_native: {
                    amount
                }
            }, fee, memo, _funds);
        };
        this.claimRewards = async (fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                claim_rewards: {}
            }, fee, memo, _funds);
        };
        this.enableClaims = async (fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                enable_claims: {}
            }, fee, memo, _funds);
        };
        this.ampReceive = async ({ ctx, messages }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                amp_receive: {
                    ctx,
                    messages
                }
            }, fee, memo, _funds);
        };
        this.ownership = async (ownershipMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                ownership: ownershipMessage
            }, fee, memo, _funds);
        };
        this.updateKernelAddress = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_kernel_address: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.updateAppContract = async ({ address }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                update_app_contract: {
                    address
                }
            }, fee, memo, _funds);
        };
        this.permissioning = async (permissioningMessage, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                permissioning: permissioningMessage
            }, fee, memo, _funds);
        };
        this.registerModule = async ({ module }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                register_module: {
                    module
                }
            }, fee, memo, _funds);
        };
        this.deregisterModule = async ({ moduleIdx }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                deregister_module: {
                    module_idx: moduleIdx
                }
            }, fee, memo, _funds);
        };
        this.alterModule = async ({ module, moduleIdx }, fee = "auto", memo, _funds) => {
            return await this.client.execute(this.sender, this.contractAddress, {
                alter_module: {
                    module,
                    module_idx: moduleIdx
                }
            }, fee, memo, _funds);
        };
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.receive = this.receive.bind(this);
        this.depositNative = this.depositNative.bind(this);
        this.withdrawNative = this.withdrawNative.bind(this);
        this.claimRewards = this.claimRewards.bind(this);
        this.enableClaims = this.enableClaims.bind(this);
        this.ampReceive = this.ampReceive.bind(this);
        this.ownership = this.ownership.bind(this);
        this.updateKernelAddress = this.updateKernelAddress.bind(this);
        this.updateAppContract = this.updateAppContract.bind(this);
        this.permissioning = this.permissioning.bind(this);
        this.registerModule = this.registerModule.bind(this);
        this.deregisterModule = this.deregisterModule.bind(this);
        this.alterModule = this.alterModule.bind(this);
    }
}
exports.LockdropContractTsClient = LockdropContractTsClient;
