/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { AssetInfoBaseForAddr, Addr, Uint128, Binary, OwnershipMessage, PermissioningMessage, AMPCtx, AMPMsg, Coin, AppContractResponse, BlockHeightResponse, KernelAddressResponse, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfString, ArrayOfPermissionInfo, SaleResponse, SaleAssetsResponse, TokenAddressResponse, TypeResponse, VersionResponse } from "./Cw20ExchangeContractTs.types";
export interface Cw20ExchangeContractTsReadOnlyInterface {
    contractAddress: string;
    sale: ({ asset }: {
        asset: AssetInfoBaseForAddr;
    }) => Promise<SaleResponse>;
    tokenAddress: () => Promise<TokenAddressResponse>;
    saleAssets: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<SaleAssetsResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export declare class Cw20ExchangeContractTsQueryClient implements Cw20ExchangeContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    sale: ({ asset }: {
        asset: AssetInfoBaseForAddr;
    }) => Promise<SaleResponse>;
    tokenAddress: () => Promise<TokenAddressResponse>;
    saleAssets: ({ limit, startAfter }: {
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<SaleAssetsResponse>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
}
export interface Cw20ExchangeContractTsInterface {
    contractAddress: string;
    sender: string;
    cancelSale: ({ asset }: {
        asset: AssetInfoBaseForAddr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    purchase: ({ recipient }: {
        recipient?: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    receive: ({ amount, msg, sender }: {
        amount: Uint128;
        msg: Binary;
        sender: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class Cw20ExchangeContractTsClient implements Cw20ExchangeContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    cancelSale: ({ asset }: {
        asset: AssetInfoBaseForAddr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    purchase: ({ recipient }: {
        recipient?: string | undefined;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    receive: ({ amount, msg, sender }: {
        amount: Uint128;
        msg: Binary;
        sender: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
