/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, PermissioningMessage, QueryMsg } from "./Cw20ExchangeContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class Cw20ExchangeContractTsExecuteMsgBuilder {
    static cancelSale: ({ asset }: CamelCasedProperties<Extract<ExecuteMsg, {
        cancel_sale: unknown;
    }>["cancel_sale"]>) => ExecuteMsg;
    static purchase: ({ recipient }: CamelCasedProperties<Extract<ExecuteMsg, {
        purchase: unknown;
    }>["purchase"]>) => ExecuteMsg;
    static receive: ({ amount, msg, sender }: CamelCasedProperties<Extract<ExecuteMsg, {
        receive: unknown;
    }>["receive"]>) => ExecuteMsg;
    static ampReceive: ({ ctx, messages }: CamelCasedProperties<Extract<ExecuteMsg, {
        amp_receive: unknown;
    }>["amp_receive"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
    static updateKernelAddress: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_kernel_address: unknown;
    }>["update_kernel_address"]>) => ExecuteMsg;
    static updateAppContract: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_app_contract: unknown;
    }>["update_app_contract"]>) => ExecuteMsg;
    static permissioning: (permissioningMessage: PermissioningMessage) => ExecuteMsg;
}
export declare abstract class Cw20ExchangeContractTsQueryMsgBuilder {
    static sale: ({ asset }: CamelCasedProperties<Extract<QueryMsg, {
        sale: unknown;
    }>["sale"]>) => QueryMsg;
    static tokenAddress: () => QueryMsg;
    static saleAssets: ({ limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        sale_assets: unknown;
    }>["sale_assets"]>) => QueryMsg;
    static owner: () => QueryMsg;
    static ownershipRequest: () => QueryMsg;
    static type: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
    static appContract: () => QueryMsg;
    static originalPublisher: () => QueryMsg;
    static blockHeightUponCreation: () => QueryMsg;
    static version: () => QueryMsg;
    static permissions: ({ actor, limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        permissions: unknown;
    }>["permissions"]>) => QueryMsg;
    static permissionedActions: () => QueryMsg;
}
