/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Uint128, MinimumFrequency, Milliseconds, AndrAddr, InstantiateMsg, CoinAndLimit, Module, ExecuteMsg, ReplyOn, Binary, OwnershipMessage, Addr, PermissioningMessage, Permission, Uint64, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, Timestamp, AccountDetails, AppContractResponse, BlockHeightResponse, CoinAllowance, KernelAddressResponse, ArrayOfString, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./RateLimitingWithdrawalsContractTs.types";
export interface RateLimitingWithdrawalsContractTsReadOnlyInterface {
  contractAddress: string;
  coinAllowanceDetails: () => Promise<CoinAllowance>;
  accountDetails: ({
    account
  }: {
    account: string;
  }) => Promise<AccountDetails>;
  owner: () => Promise<ContractOwnerResponse>;
  ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
  type: () => Promise<TypeResponse>;
  kernelAddress: () => Promise<KernelAddressResponse>;
  appContract: () => Promise<AppContractResponse>;
  originalPublisher: () => Promise<PublisherResponse>;
  blockHeightUponCreation: () => Promise<BlockHeightResponse>;
  version: () => Promise<VersionResponse>;
  permissions: ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfPermissionInfo>;
  permissionedActions: () => Promise<ArrayOfString>;
  module: ({
    id
  }: {
    id: Uint64;
  }) => Promise<Module>;
  moduleIds: () => Promise<ArrayOfString>;
}
export class RateLimitingWithdrawalsContractTsQueryClient implements RateLimitingWithdrawalsContractTsReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.coinAllowanceDetails = this.coinAllowanceDetails.bind(this);
    this.accountDetails = this.accountDetails.bind(this);
    this.owner = this.owner.bind(this);
    this.ownershipRequest = this.ownershipRequest.bind(this);
    this.type = this.type.bind(this);
    this.kernelAddress = this.kernelAddress.bind(this);
    this.appContract = this.appContract.bind(this);
    this.originalPublisher = this.originalPublisher.bind(this);
    this.blockHeightUponCreation = this.blockHeightUponCreation.bind(this);
    this.version = this.version.bind(this);
    this.permissions = this.permissions.bind(this);
    this.permissionedActions = this.permissionedActions.bind(this);
    this.module = this.module.bind(this);
    this.moduleIds = this.moduleIds.bind(this);
  }

  coinAllowanceDetails = async (): Promise<CoinAllowance> => {
    return this.client.queryContractSmart(this.contractAddress, {
      coin_allowance_details: {}
    });
  };
  accountDetails = async ({
    account
  }: {
    account: string;
  }): Promise<AccountDetails> => {
    return this.client.queryContractSmart(this.contractAddress, {
      account_details: {
        account
      }
    });
  };
  owner = async (): Promise<ContractOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  ownershipRequest = async (): Promise<ContractPotentialOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership_request: {}
    });
  };
  type = async (): Promise<TypeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      type: {}
    });
  };
  kernelAddress = async (): Promise<KernelAddressResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      kernel_address: {}
    });
  };
  appContract = async (): Promise<AppContractResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      app_contract: {}
    });
  };
  originalPublisher = async (): Promise<PublisherResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      original_publisher: {}
    });
  };
  blockHeightUponCreation = async (): Promise<BlockHeightResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_height_upon_creation: {}
    });
  };
  version = async (): Promise<VersionResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      version: {}
    });
  };
  permissions = async ({
    actor,
    limit,
    startAfter
  }: {
    actor: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfPermissionInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        actor,
        limit,
        start_after: startAfter
      }
    });
  };
  permissionedActions = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissioned_actions: {}
    });
  };
  module = async ({
    id
  }: {
    id: Uint64;
  }): Promise<Module> => {
    return this.client.queryContractSmart(this.contractAddress, {
      module: {
        id
      }
    });
  };
  moduleIds = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      module_ids: {}
    });
  };
}
export interface RateLimitingWithdrawalsContractTsInterface {
  contractAddress: string;
  sender: string;
  deposits: ({
    recipient
  }: {
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdrawFunds: ({
    amount
  }: {
    amount: Uint128;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ampReceive: ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateKernelAddress: ({
    address
  }: {
    address: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAppContract: ({
    address
  }: {
    address: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerModule: ({
    module
  }: {
    module: Module;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  deregisterModule: ({
    moduleIdx
  }: {
    moduleIdx: Uint64;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  alterModule: ({
    module,
    moduleIdx
  }: {
    module: Module;
    moduleIdx: Uint64;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class RateLimitingWithdrawalsContractTsClient implements RateLimitingWithdrawalsContractTsInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.deposits = this.deposits.bind(this);
    this.withdrawFunds = this.withdrawFunds.bind(this);
    this.ampReceive = this.ampReceive.bind(this);
    this.ownership = this.ownership.bind(this);
    this.updateKernelAddress = this.updateKernelAddress.bind(this);
    this.updateAppContract = this.updateAppContract.bind(this);
    this.permissioning = this.permissioning.bind(this);
    this.registerModule = this.registerModule.bind(this);
    this.deregisterModule = this.deregisterModule.bind(this);
    this.alterModule = this.alterModule.bind(this);
  }

  deposits = async ({
    recipient
  }: {
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposits: {
        recipient
      }
    }, fee, memo, _funds);
  };
  withdrawFunds = async ({
    amount
  }: {
    amount: Uint128;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_funds: {
        amount
      }
    }, fee, memo, _funds);
  };
  ampReceive = async ({
    ctx,
    messages
  }: {
    ctx: AMPCtx;
    messages: AMPMsg[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      amp_receive: {
        ctx,
        messages
      }
    }, fee, memo, _funds);
  };
  ownership = async (ownershipMessage: OwnershipMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      ownership: ownershipMessage
    }, fee, memo, _funds);
  };
  updateKernelAddress = async ({
    address
  }: {
    address: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_kernel_address: {
        address
      }
    }, fee, memo, _funds);
  };
  updateAppContract = async ({
    address
  }: {
    address: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_app_contract: {
        address
      }
    }, fee, memo, _funds);
  };
  permissioning = async (permissioningMessage: PermissioningMessage, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      permissioning: permissioningMessage
    }, fee, memo, _funds);
  };
  registerModule = async ({
    module
  }: {
    module: Module;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_module: {
        module
      }
    }, fee, memo, _funds);
  };
  deregisterModule = async ({
    moduleIdx
  }: {
    moduleIdx: Uint64;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deregister_module: {
        module_idx: moduleIdx
      }
    }, fee, memo, _funds);
  };
  alterModule = async ({
    module,
    moduleIdx
  }: {
    module: Module;
    moduleIdx: Uint64;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      alter_module: {
        module,
        module_idx: moduleIdx
      }
    }, fee, memo, _funds);
  };
}