/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, MinimumFrequency, Milliseconds, AndrAddr, InstantiateMsg, CoinAndLimit, Module, ExecuteMsg, ReplyOn, Binary, OwnershipMessage, Addr, PermissioningMessage, Permission, Uint64, AMPPkt, AMPCtx, AMPMsg, AMPMsgConfig, IBCConfig, Coin, QueryMsg, Timestamp, AccountDetails, AppContractResponse, BlockHeightResponse, CoinAllowance, KernelAddressResponse, ArrayOfString, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, PermissionInfo, TypeResponse, VersionResponse } from "./RateLimitingWithdrawalsContractTs.types";
import { CamelCasedProperties } from "type-fest";
export abstract class RateLimitingWithdrawalsContractTsExecuteMsgBuilder {
  static deposits = ({
    recipient
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deposits: unknown;
  }>["deposits"]>): ExecuteMsg => {
    return {
      deposits: ({
        recipient
      } as const)
    };
  };
  static withdrawFunds = ({
    amount
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw_funds: unknown;
  }>["withdraw_funds"]>): ExecuteMsg => {
    return {
      withdraw_funds: ({
        amount
      } as const)
    };
  };
  static ampReceive = ({
    ctx,
    messages
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    amp_receive: unknown;
  }>["amp_receive"]>): ExecuteMsg => {
    return {
      amp_receive: ({
        ctx,
        messages
      } as const)
    };
  };
  static ownership = (ownershipMessage: OwnershipMessage): ExecuteMsg => {
    return {
      ownership: ownershipMessage
    };
  };
  static updateKernelAddress = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_kernel_address: unknown;
  }>["update_kernel_address"]>): ExecuteMsg => {
    return {
      update_kernel_address: ({
        address
      } as const)
    };
  };
  static updateAppContract = ({
    address
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_app_contract: unknown;
  }>["update_app_contract"]>): ExecuteMsg => {
    return {
      update_app_contract: ({
        address
      } as const)
    };
  };
  static permissioning = (permissioningMessage: PermissioningMessage): ExecuteMsg => {
    return {
      permissioning: permissioningMessage
    };
  };
  static registerModule = ({
    module
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    register_module: unknown;
  }>["register_module"]>): ExecuteMsg => {
    return {
      register_module: ({
        module
      } as const)
    };
  };
  static deregisterModule = ({
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    deregister_module: unknown;
  }>["deregister_module"]>): ExecuteMsg => {
    return {
      deregister_module: ({
        module_idx: moduleIdx
      } as const)
    };
  };
  static alterModule = ({
    module,
    moduleIdx
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    alter_module: unknown;
  }>["alter_module"]>): ExecuteMsg => {
    return {
      alter_module: ({
        module,
        module_idx: moduleIdx
      } as const)
    };
  };
}
export abstract class RateLimitingWithdrawalsContractTsQueryMsgBuilder {
  static coinAllowanceDetails = (): QueryMsg => {
    return {
      coin_allowance_details: ({} as const)
    };
  };
  static accountDetails = ({
    account
  }: CamelCasedProperties<Extract<QueryMsg, {
    account_details: unknown;
  }>["account_details"]>): QueryMsg => {
    return {
      account_details: ({
        account
      } as const)
    };
  };
  static owner = (): QueryMsg => {
    return {
      owner: ({} as const)
    };
  };
  static ownershipRequest = (): QueryMsg => {
    return {
      ownership_request: ({} as const)
    };
  };
  static type = (): QueryMsg => {
    return {
      type: ({} as const)
    };
  };
  static kernelAddress = (): QueryMsg => {
    return {
      kernel_address: ({} as const)
    };
  };
  static appContract = (): QueryMsg => {
    return {
      app_contract: ({} as const)
    };
  };
  static originalPublisher = (): QueryMsg => {
    return {
      original_publisher: ({} as const)
    };
  };
  static blockHeightUponCreation = (): QueryMsg => {
    return {
      block_height_upon_creation: ({} as const)
    };
  };
  static version = (): QueryMsg => {
    return {
      version: ({} as const)
    };
  };
  static permissions = ({
    actor,
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    permissions: unknown;
  }>["permissions"]>): QueryMsg => {
    return {
      permissions: ({
        actor,
        limit,
        start_after: startAfter
      } as const)
    };
  };
  static permissionedActions = (): QueryMsg => {
    return {
      permissioned_actions: ({} as const)
    };
  };
  static module = ({
    id
  }: CamelCasedProperties<Extract<QueryMsg, {
    module: unknown;
  }>["module"]>): QueryMsg => {
    return {
      module: ({
        id
      } as const)
    };
  };
  static moduleIds = (): QueryMsg => {
    return {
      module_ids: ({} as const)
    };
  };
}