/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, OwnershipMessage, QueryMsg } from "./VfsContractTs.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class VfsContractTsExecuteMsgBuilder {
    static addPath: ({ address, name, parentAddress }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_path: unknown;
    }>["add_path"]>) => ExecuteMsg;
    static addSymlink: ({ name, parentAddress, symlink }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_symlink: unknown;
    }>["add_symlink"]>) => ExecuteMsg;
    static addChild: ({ name, parentAddress }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_child: unknown;
    }>["add_child"]>) => ExecuteMsg;
    static registerUser: ({ address, username }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_user: unknown;
    }>["register_user"]>) => ExecuteMsg;
    static registerLibrary: ({ libAddress, libName }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_library: unknown;
    }>["register_library"]>) => ExecuteMsg;
    static registerUserCrossChain: ({ address, chain }: CamelCasedProperties<Extract<ExecuteMsg, {
        register_user_cross_chain: unknown;
    }>["register_user_cross_chain"]>) => ExecuteMsg;
    static ownership: (ownershipMessage: OwnershipMessage) => ExecuteMsg;
}
export declare abstract class VfsContractTsQueryMsgBuilder {
    static resolvePath: ({ path }: CamelCasedProperties<Extract<QueryMsg, {
        resolve_path: unknown;
    }>["resolve_path"]>) => QueryMsg;
    static subDir: ({ limit, max, min, path }: CamelCasedProperties<Extract<QueryMsg, {
        sub_dir: unknown;
    }>["sub_dir"]>) => QueryMsg;
    static paths: ({ addr }: CamelCasedProperties<Extract<QueryMsg, {
        paths: unknown;
    }>["paths"]>) => QueryMsg;
    static getUsername: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        get_username: unknown;
    }>["get_username"]>) => QueryMsg;
    static getLibrary: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        get_library: unknown;
    }>["get_library"]>) => QueryMsg;
    static resolveSymlink: ({ path }: CamelCasedProperties<Extract<QueryMsg, {
        resolve_symlink: unknown;
    }>["resolve_symlink"]>) => QueryMsg;
    static version: () => QueryMsg;
    static type: () => QueryMsg;
    static owner: () => QueryMsg;
    static kernelAddress: () => QueryMsg;
}
