/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Module, Binary, Uint128, OwnershipMessage, Uint64, Addr, PermissioningMessage, AMPCtx, AMPMsg, Coin, AppContractResponse, BlockHeightResponse, KernelAddressResponse, SaleStateResponse, ArrayOfString, PublisherResponse, ContractOwnerResponse, ContractPotentialOwnerResponse, ArrayOfPermissionInfo, SaleIdsResponse, ArrayOfSaleInfo, TypeResponse, VersionResponse } from "./MarketplaceContractTs.types";
export interface MarketplaceContractTsReadOnlyInterface {
    contractAddress: string;
    latestSaleState: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }) => Promise<SaleStateResponse>;
    saleState: ({ saleId }: {
        saleId: Uint128;
    }) => Promise<SaleStateResponse>;
    saleIds: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }) => Promise<SaleIdsResponse>;
    saleInfosForAddress: ({ limit, startAfter, tokenAddress }: {
        limit?: number;
        startAfter?: string;
        tokenAddress: string;
    }) => Promise<ArrayOfSaleInfo>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number;
        startAfter?: string;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
    module: ({ id }: {
        id: Uint64;
    }) => Promise<Module>;
    moduleIds: () => Promise<ArrayOfString>;
}
export declare class MarketplaceContractTsQueryClient implements MarketplaceContractTsReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    latestSaleState: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }) => Promise<SaleStateResponse>;
    saleState: ({ saleId }: {
        saleId: Uint128;
    }) => Promise<SaleStateResponse>;
    saleIds: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }) => Promise<SaleIdsResponse>;
    saleInfosForAddress: ({ limit, startAfter, tokenAddress }: {
        limit?: number | undefined;
        startAfter?: string | undefined;
        tokenAddress: string;
    }) => Promise<ArrayOfSaleInfo>;
    owner: () => Promise<ContractOwnerResponse>;
    ownershipRequest: () => Promise<ContractPotentialOwnerResponse>;
    type: () => Promise<TypeResponse>;
    kernelAddress: () => Promise<KernelAddressResponse>;
    appContract: () => Promise<AppContractResponse>;
    originalPublisher: () => Promise<PublisherResponse>;
    blockHeightUponCreation: () => Promise<BlockHeightResponse>;
    version: () => Promise<VersionResponse>;
    permissions: ({ actor, limit, startAfter }: {
        actor: string;
        limit?: number | undefined;
        startAfter?: string | undefined;
    }) => Promise<ArrayOfPermissionInfo>;
    permissionedActions: () => Promise<ArrayOfString>;
    module: ({ id }: {
        id: Uint64;
    }) => Promise<Module>;
    moduleIds: () => Promise<ArrayOfString>;
}
export interface MarketplaceContractTsInterface {
    contractAddress: string;
    sender: string;
    receiveNft: ({ msg, sender, tokenId }: {
        msg: Binary;
        sender: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    buy: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateSale: ({ coinDenom, price, tokenAddress, tokenId }: {
        coinDenom: string;
        price: Uint128;
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    cancelSale: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    registerModule: ({ module }: {
        module: Module;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    deregisterModule: ({ moduleIdx }: {
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    alterModule: ({ module, moduleIdx }: {
        module: Module;
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class MarketplaceContractTsClient implements MarketplaceContractTsInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    receiveNft: ({ msg, sender, tokenId }: {
        msg: Binary;
        sender: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    buy: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateSale: ({ coinDenom, price, tokenAddress, tokenId }: {
        coinDenom: string;
        price: Uint128;
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    cancelSale: ({ tokenAddress, tokenId }: {
        tokenAddress: string;
        tokenId: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ampReceive: ({ ctx, messages }: {
        ctx: AMPCtx;
        messages: AMPMsg[];
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    ownership: (ownershipMessage: OwnershipMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateKernelAddress: ({ address }: {
        address: Addr;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    updateAppContract: ({ address }: {
        address: string;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    permissioning: (permissioningMessage: PermissioningMessage, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    registerModule: ({ module }: {
        module: Module;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    deregisterModule: ({ moduleIdx }: {
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
    alterModule: ({ module, moduleIdx }: {
        module: Module;
        moduleIdx: Uint64;
    }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
