/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Logo = {
  url: string;
} | {
  embedded: EmbeddedLogo;
};
export type EmbeddedLogo = {
  svg: Binary;
} | {
  png: Binary;
};
export type Binary = string;
export type AndrAddr = string;
export interface InstantiateMsg {
  decimals: number;
  initial_balances: Cw20Coin[];
  kernel_address: string;
  marketing?: InstantiateMarketingInfo | null;
  mint?: MinterResponse | null;
  modules?: Module[] | null;
  name: string;
  owner?: string | null;
  symbol: string;
}
export interface Cw20Coin {
  address: string;
  amount: Uint128;
}
export interface InstantiateMarketingInfo {
  description?: string | null;
  logo?: Logo | null;
  marketing?: string | null;
  project?: string | null;
}
export interface MinterResponse {
  cap?: Uint128 | null;
  minter: string;
}
export interface Module {
  address: AndrAddr;
  is_mutable: boolean;
  name?: string | null;
}
export type ExecuteMsg = {
  transfer: {
    amount: Uint128;
    recipient: AndrAddr;
  };
} | {
  burn: {
    amount: Uint128;
  };
} | {
  send: {
    amount: Uint128;
    contract: AndrAddr;
    msg: Binary;
  };
} | {
  increase_allowance: {
    amount: Uint128;
    expires?: Expiration | null;
    spender: string;
  };
} | {
  decrease_allowance: {
    amount: Uint128;
    expires?: Expiration | null;
    spender: string;
  };
} | {
  transfer_from: {
    amount: Uint128;
    owner: string;
    recipient: AndrAddr;
  };
} | {
  send_from: {
    amount: Uint128;
    contract: AndrAddr;
    msg: Binary;
    owner: string;
  };
} | {
  burn_from: {
    amount: Uint128;
    owner: string;
  };
} | {
  mint: {
    amount: Uint128;
    recipient: string;
  };
} | {
  update_marketing: {
    description?: string | null;
    marketing?: string | null;
    project?: string | null;
  };
} | {
  upload_logo: Logo;
} | {
  amp_receive: AMPPkt;
} | {
  ownership: OwnershipMessage;
} | {
  update_kernel_address: {
    address: Addr;
  };
} | {
  update_app_contract: {
    address: string;
  };
} | {
  permissioning: PermissioningMessage;
} | {
  register_module: {
    module: Module;
  };
} | {
  deregister_module: {
    module_idx: Uint64;
  };
} | {
  alter_module: {
    module: Module;
    module_idx: Uint64;
  };
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type ReplyOn = "always" | "error" | "success" | "never";
export type OwnershipMessage = ("revoke_ownership_offer" | "accept_ownership" | "disown") | {
  update_owner: {
    expiration?: Milliseconds | null;
    new_owner: Addr;
  };
};
export type Milliseconds = number;
export type Addr = string;
export type PermissioningMessage = {
  set_permission: {
    action: string;
    actor: AndrAddr;
    permission: Permission;
  };
} | {
  remove_permission: {
    action: string;
    actor: AndrAddr;
  };
} | {
  permission_action: {
    action: string;
  };
} | {
  disable_action_permissioning: {
    action: string;
  };
};
export type Permission = {
  blacklisted: Milliseconds | null;
} | {
  limited: {
    expiration?: Milliseconds | null;
    uses: number;
  };
} | {
  whitelisted: Milliseconds | null;
};
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id: number;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_sender: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  token_info: {};
} | {
  minter: {};
} | {
  allowance: {
    owner: string;
    spender: string;
  };
} | {
  all_allowances: {
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  all_accounts: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  marketing_info: {};
} | {
  download_logo: {};
} | {
  balance: {
    address: string;
  };
} | {
  owner: {};
} | {
  ownership_request: {};
} | {
  type: {};
} | {
  kernel_address: {};
} | {
  app_contract: {};
} | {
  original_publisher: {};
} | {
  block_height_upon_creation: {};
} | {
  version: {};
} | {
  permissions: {
    actor: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  permissioned_actions: {};
} | {
  module: {
    id: Uint64;
  };
} | {
  module_ids: {};
};
export interface AllAccountsResponse {
  accounts: string[];
  [k: string]: unknown;
}
export interface AllAllowancesResponse {
  allowances: AllowanceInfo[];
  [k: string]: unknown;
}
export interface AllowanceInfo {
  allowance: Uint128;
  expires: Expiration;
  spender: string;
}
export interface AllowanceResponse {
  allowance: Uint128;
  expires: Expiration;
  [k: string]: unknown;
}
export interface AppContractResponse {
  app_contract: Addr;
}
export interface BalanceResponse {
  balance: Uint128;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface DownloadLogoResponse {
  data: Binary;
  mime_type: string;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export type LogoInfo = {
  url: string;
} | "embedded";
export interface MarketingInfoResponse {
  description?: string | null;
  logo?: LogoInfo | null;
  marketing?: Addr | null;
  project?: string | null;
  [k: string]: unknown;
}
export type ArrayOfString = string[];
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface ContractPotentialOwnerResponse {
  expiration?: Milliseconds | null;
  potential_owner?: Addr | null;
}
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export interface TokenInfoResponse {
  decimals: number;
  name: string;
  symbol: string;
  total_supply: Uint128;
}
export interface TypeResponse {
  ado_type: string;
}
export interface VersionResponse {
  version: string;
}
export type Cw20ContractTsExecuteMsg = ExecuteMsg;